### ISSUE TITLE
Storefront documentation

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#169]
_Update_: Using Vuepress

https://developers.e-com.plus/storefront/

---

Choose the right tool, setup devops and initial doc files for template usage/customization.

Documentation will include:
- Base UI reference and colors guide;
- Vue components references and examples;
- Storefront global variables and events;
- Guide/examples for _advanced_ customization with Webpack aliases;
- Netlify CMS mention, default config and how to customize;
- Guide/examples for creating new widgets;

Which and why?
1. Storybook
2. Vuepress
3. Vuese / Vue styleguidist
4. Start from Bootstrap 4 docs, add things for Vue components (seems laborious)
5. _Another (?)_

> After that we can start documenting base UI  with [`@ecomplus/storefront-twbs`](https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-twbs) https://github.com/ecomplus/storefront/issues/168

**Comment by leomp12** [comment]
Documentation source should be a new (private) package managed by Lerna to run tests with local package versions.

We can create a `documentation` folder on root dir and add `documentation/*` to packages:
https://github.com/ecomplus/storefront/blob/master/lerna.json#L3

**Comment by leomp12** [comment]
Storybook seems to be more for tests then documentation itself, and as we're going to write large documentation with very different sections, **I'm tending to [Vuepress](https://vuepress.vuejs.org/)** because it's simpler and can document almost anything (not only components reference)...

**Comment by thiagoabreudev** [comment]
I agree. I believe that the storybook can be added later as a playground if necessary.

**Comment by leomp12** [comment]
https://developers.e-com.plus/storefront/

TODOs:

- [ ] Sidebar with links for each package

**Comment by leomp12** [comment]
:up: Update Vuepress sidebar/nav with packages and topics properly ordered.

**Comment by leomp12** [comment]
:next_track_button:  Doc parts were listed on project https://github.com/ecomplus/storefront/projects/3 and should be converted to issues with respective checklist (such as https://github.com/ecomplus/storefront/issues/168).
