### ISSUE TITLE
[RFC] Customization

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#177]
How Storefront V2 may be customized (from easier to harder) and TODOs:

1. Insert HTML, JS and CSS with specified files predefined at [Storefront Starter](https://github.com/ecomplus/storefront-starter):

    - Split [`views`](https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-template/template/pages/%40/views) in new partials to make possible to insert HTML in more (any) places;
    - Update Storefront Starter [`pages`](https://github.com/ecomplus/storefront-starter/tree/master/template/pages) with new _insert_ partials and respective imports;

> :no_entry_sign: Update: new (better) approach with Storefront Starter git update https://github.com/ecomplus/storefront-starter/issues/119

2. Edit prerendered HTML through EJS or dynamically update DOM with custom JS (can use jQuery):

    - Template EJS [`components`](https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-template/template/pages/%40/views/components) may have predefined places for additional HTML;
    - [Vue components](https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-components/src/html) must have slots to support most common additional HTML cases (https://github.com/ecomplus/storefront/issues/167);
    - Widgets must try to keep custom prerendered HTML, preferably trough respective component slots;

> Update: tracked on https://github.com/ecomplus/storefront/issues/191

3. Use Webpack aliases on `storefront.webpack.js` to make deeper edits on Vue component parts (HTML, JS or SCSS);

**Comment by leomp12** [comment]
@matheusgnreis take a look here please

**Comment by leomp12** [comment]
@thiagoabreudev @ThaisChaves it'll alse be included to docs (https://github.com/ecomplus/storefront/issues/169)

**Comment by matheusgnreis** [comment]
Only one of them? I think they complete each other, with storefront.webpack.js we can do deeper edits, just like you said. 
- Split views in new partials to make possible to insert HTML in more (any) places, i think is important too. Today is only at top or bottom. Shoppers like to insert some banners between some stuff, like 'vitrine' or between them and slide.
-Use of jquery for some shoppers, may be helpful

**Comment by leomp12** [comment]
@matheusgnreis not only one, all of 3 ways, I've just listed sorted by easier to harder (in my vision), but idea is to support all those customization strategies with easy (as possible).

**Comment by leomp12** [comment]
Related to EJS includes for our widgets and components customization (such as Vue slots) https://github.com/mde/ejs/issues/500

**Comment by leomp12** [comment]
Thinking about moving entire EJS (`pages`) to Storefront Starter and use Git programmatically to make updates, it would prevent needing to copy and paste EJS code to edit.
I'm just not sure yet if it can be consistent without having to do lot of work to implement :thinking:
