### ISSUE TITLE
Error with first access with social login

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#179]
After trying to login at first time into passport, i select my account, log in and then nothing happen, just url just like this photo:

![Captura de tela de 2020-03-16 17-23-16](https://user-images.githubusercontent.com/35343551/76801400-5bca9a00-67b4-11ea-96e3-222e1e9fe409.png)

To pass to another page to continue the register i have to click f5 and then i go to the correct page and works, just like this photo:

![Captura de tela de 2020-03-16 17-23-38](https://user-images.githubusercontent.com/35343551/76801404-5e2cf400-67b4-11ea-9720-24ee26520397.png)

See that the url is the same before, but just work when i click f5

**Comment by matheusgnreis** [comment]
No mobile safari, agora eu consigo logar, não dá mais aquele erro de aparecia em tela

**Comment by matheusgnreis** [comment]
Somente esse ai que continua

**Comment by leomp12** [comment]
@matheusgnreis pode testar isso de novo por favor? Só na loja demo por enquanto.
