### ISSUE TITLE
sort menu orders

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#197]
It was an bug when i put a sort at menu.json it became inverted. So after 2 weeks this bug was fixed, it became to inverted. So tia sonia ask me, and i change the words. Recently i open the website and see another order again. And last week became inverted and now according to https://community.e-com.plus/t/ordem-das-categorias/213/15 is floating between to orders

**Comment by matheusgnreis** [comment]
Rolou de novo, estou com print aqui, mas como falou que no seu local está tudo certo, informei a ele lá que quando sair o v2, deve funcionar

**Comment by leomp12** [comment]
Eu vi na loja Kelvys, na verdade também estava certo em dev server na v1, mas eu fechei o issue com um commit: _leomp12 closed this in [e1f7bd1](https://github.com/ecomplus/storefront/commit/e1f7bd13e7822f21e16f6d85a812b2b98b07f038) 3 minutes ago_
Acho que vai resolver.

**Comment by leomp12** [comment]
Só pra V2 mesmo.

**Comment by matheusgnreis** [comment]
Beleza, falei certo então lá
