### ISSUE TITLE
Avisa-me quando chegar

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#216]
Inserção do avisa-me quando chegar em produtos que acabaram estoque. Acredito que o envio de email seja mais importante, pelo menos foi assim que já vi funcionar em outros lugares. Solicitação vide https://community.e-com.plus/t/avise-me-quando-chegar/178/5

**Comment by leomp12** [comment]
Hum, talvez push seria mais eficaz, não? De qualquer forma é necessário um widget novo no CMS, talvez um app novo e claro a implementação no componente Vue `TheProduct`.

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/e1f15103c9a1095c80df5b61f7c61c55108cacbf
