### ISSUE TITLE
Criar coleções automáticas de ofertas e lançamentos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#217]
Conforme os produtos entrarem em ofertas, mostrar uma vitrine de produtos em oferta. Assim como produtos em lançamento. Vide tópico https://community.e-com.plus/t/grid-ofertas-como-na-e-com-club/241

**Comment by leomp12** [comment]
Relacionado ao componente `TheProduct`.

**Comment by leomp12** [comment]
https://github.com/ecomplus/search-engine/issues/34

**Comment by matheusgnreis** [comment]
Voltaram a solicitar isso na comunidade, uma coleção automática, como se fosse de produto relacionados com novidades e outra com ofertas.
