### ISSUE TITLE
Inserir variação com inputs

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#225]
Permitir que seja renderizado variação com input de texto na loja, onde o cliente do lojista poderá inserir um nome, ou qualquer outro texto. Vide sugestão da comunidade:
https://community.e-com.plus/t/campo-para-personalizados/293

**Comment by leomp12** [comment]
Na verdade isso aqui tem que começar no painel ainda, depois alterações no checkout (API de módulos), só depois uma feature pro Storefront, faz sentido?

**Comment by matheusgnreis** [comment]
Sim, pensei nisso também, vou criar lá

**Comment by leomp12** [comment]
https://github.com/ecomplus/admin/issues/115

**Comment by leomp12** [comment]
@talissonf anima nos dar uma força com isso aqui?

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/90ea59f069578abaa341d31e7e7af9f283d0b358
