### ISSUE TITLE
Organizar forma de pagamento no checkout

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#239]
Ao invés das formas de pagamento aparecerem de forma aleatória no checkout, manter em uma mesma posição, se possível poder ter a escolha de qual forma de pagamento irá aparecer primeiro. Vide https://community.e-com.plus/t/fixar-formas-de-pagamento/309

**Comment by leomp12** [comment]
Dá pra mockar com JS, ex:

```js
window.ecomPaymentApps = [1245, 9001, 9004]
```

Falta adicionar ao CMS.

**Comment by leomp12** [comment]
@matheusgnreis estes números são os `app_id` de cada aplicativo de pagamento.

**Comment by matheusgnreis** [comment]
No caso seria um widget pra isso né?

**Comment by matheusgnreis** [comment]
Se for, posso tentar fazer aqui com base nos que tem de categoria por exemplo

**Comment by matheusgnreis** [comment]
Vou tentar aqui, se alguem tiver muito desesperado, mocko lá

**Comment by leomp12** [comment]
> No caso seria um widget pra isso né?

Não seria um widget, na verdade temos que criar uma entrada nova lá pra configuração do checkout, incluindo isto das formas de pagamento.
