### ISSUE TITLE
Variar imagem conforme varia variação

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#242]
Alterar o componente ``` ProductVariations ``` para emitir um evento com a imagem selecionada para o ```APicture ```
Pensei numa gambi, mas já que não gosta disso, vou nem colocar aqui

**Comment by leomp12** [comment]
kkkkk gambi não é bom @matheusgnreis

**Comment by leomp12** [comment]
Código lindão desse e você quer fazeer gambiarra
