### ISSUE TITLE
Mobile view banners

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#247]
**Is your feature request related to a problem? Please describe.**
Lighthouse new LCP metric is not so good (unstable) and banners for desktop on mobile are not so pretty, I think we can make it better by replacing the homepage slider banners for mobile.

**Describe the solution you'd like**
Just upload new banner images (webp and png) for slider on mobile specifically, then set in on `home.json` content using `mobile_img` field :cake: 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by leomp12** [comment]
@vitorrgg podia fazer isso aqui um dia em, me dá uma mão aí pra aumentar performance no Lighthouse da demo :grin:

**Comment by vitorrgg** [comment]
![passion](https://user-images.githubusercontent.com/35348281/90399118-d1db7180-e070-11ea-95f9-b3dbc91314a7.png)
![headphone](https://user-images.githubusercontent.com/35348281/90399129-d4d66200-e070-11ea-94c6-8cbb35611939.png)

**Comment by leomp12** [comment]
@vitorrgg na verdade o tiro saiu pela colatra porque você colocou uma imagem 1080x1080 e ficou até mais pesada do que a anterior :neutral_face: 
Uma imagem só pra mobile deve ter no máximo (estourando) 576px de largura, 1080px já é um dektop (nem tablet)...
