### ISSUE TITLE
Custom CMS logo

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#250]
**Is your feature request related to a problem? Please describe.**
Netlify CMS logo (only) is confusing for our merchants and bad for our branding.

**Describe the solution you'd like**
On default CMS config we can [set a custom logo](https://www.netlifycms.org/docs/configuration-options/#custom-logo) merging Storefront + E-Com Plus + Netlify CMS (deserve credits too) logos.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vitorrgg** [comment]
![cmslogo](https://user-images.githubusercontent.com/35348281/84186191-8ef49080-aa66-11ea-9a97-5205c4166073.png)

**Comment by leomp12** [comment]
@vitorrgg podia ter criado a PR já em haha

**Comment by vitorrgg** [comment]
![cmslogo](https://user-images.githubusercontent.com/35348281/84193238-7d64b600-aa71-11ea-88c6-0063ab213d95.png)
