### ISSUE TITLE
Inserir filtro na estante de produtos para não buscar produtos sem estoque

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#274]
Existem lojas que preferem mostrar produtos sem estoque, pois é um produto constantemente vendido e havendo mais demanda, ele irão colocar para criar mais produtos deste, mas existem outros que preferem não mostrar, então poderia ter um filtro, assim como consta para mostrar mais vendidos, promoções, ter um que filtro por produtos que tenham estoque

**Comment by leomp12** [comment]
Na verdade o que tem são opções de ordenação, aqui seria uma opção de filtro...

**Comment by leomp12** [comment]
@matheusgnreis na verdade não sei se este issue é pertinente porque já usamos o `EcomSearch` pra listar os produtos da coleção [aqui](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/pages/%40/sections/collection-shelf.ejs#L19), e o `EcomSearch` já prefere produtos com estoque por padrão, já é critério de ordenação antes da opção por vendas, popularidade, preço e etc...

Podemos adicionar a opção de filtro, mas aí os produtos sem estoque não aparecerão de forma alguma e a estante pode ficar vazia, é isto mesmo?

> Note que isto é pré-renderizado, ou seja, a estante pode ser renderizada só com produtos em estoque e posteriormente aparecer um ou outro sem estoque se tiver sido vendido e ainda não tiver ocorrido outra renderização.

**Comment by matheusgnreis** [comment]
Seria a estante de produtos, o "plugin". Veja a vitrine da Fabi por exemplo:
![artestore-vitrine](https://user-images.githubusercontent.com/35343551/92262352-5de2fb00-eeb1-11ea-891f-84fc3b90932a.png)
Ao passar para o lado, mostram produtos com estoque, então a sugestão dela e de outras era que pudesse aparecer somente com estoque. Logo fica destacado aquilo que não tem, essa foi a ideia de mostrar só que está com estoque para ser vendido

**Comment by leomp12** [comment]
@matheusgnreis aparece sem estoque porque a coleção que ela colocou tem 8 produtos apenas:

```json
["5ec1c382126b0d057213c27d","5ec1b983126b0d057213c0e8","5ec1b9dd126b0d057213c0f6","5f1b43efe13b0242bdc473ce","5f19d8a614ff772fde81d3c9","5f19d9fc14ff772fde81d3f9","5f16326614ff772fde8119b6","5f16355914ff772fde811afb"]
```

Portanto os 8 serão adicionados à estante, se tivesse mais seriam selecionados primeiro os produtos com estoque.
Além disto, a estante está com a opção _embaralhar_ [ativa](https://github.com/ecomplus-stores/artestore/blob/master/content/home.json#L39), se não os 2 produtos sem estoque desta coleção apereceriam após os 6 com estoque, como está embaralhado vai variar.

**Comment by leomp12** [comment]
@matheusgnreis vou fechar o issue porque como te expliquei acima, pelo menos neste caso eh soh uma questao de configuracao da colecao e da section no CMS...
