### ISSUE TITLE
Destinatário aparecer nome completo

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#278]
Na geração de etiqueta por exemplo busca-se o nome do destinatário se houver, como ele fica por padrão no checkout com primeiro nome, na etiqueta vai apenas com primeiro nome. Isso influencia também demais integrações de ERP, onde envia o nome do cliente e o nome do destinatário. Se for o mesmo, o cliente não coloca novamente o sobrenome. Agora se for diferente ele talvez coloque diferente. Por isso é interessante aparecer o nome completo.

**Comment by leomp12** [comment]
Não entendi, à priopri o destinatário não precisa do nome completo uai, mesmo que o destinatário seja diferente do comprador. Precisa do nome completo é pra NF...

**Comment by leomp12** [comment]
O destinatário ali é só pra identificação na hora da entrega, não pra emissão de documento nenhum, se está usando desta forma em algum ERP talvez a integração que está errada.

**Comment by matheusgnreis** [comment]
Então na e-com plus não tem destinatário diferente do comprador? Isso pode gerar problema então, porque aparentemente ali considera-se o comprador, mas fica editável pra inserir qualquer nome.

**Comment by matheusgnreis** [comment]
O destinatário ali é só pra identificação na hora da entrega por parte da transportadora, não pra emissão de documento nenhum, se está usando desta forma em algum ERP talvez a integração que está errada. 

Estava acontecendo, eu avisei o talisson, acredito que tenha corrigido

**Comment by leomp12** [comment]
> Então na e-com plus não tem destinatário diferente do comprador? Isso pode gerar problema então, porque aparentemente ali considera-se o comprador, mas fica editável pra inserir qualquer nome.

Tem, claro, por isto mesmo o destinatário pode ficar apenas com o nome, sem sobrenome, em teoria ele só vái na etiqueta de envio então por isto o sobrenome é opcional.
A NF deve ser emitida em nome do comprador, este sim sempre com nome completo.
Também pode haver uma terceira pessoa como pagador se o cartão não for do comprador...

**Comment by leomp12** [comment]
Não que o destinatário não deva ser enviado para o ERP, só deve ir no campo correto sem substituir o nome completo do comprador, a NFe sempre deverá ser emitida com o nome completo do comprador no objeto `buyers[i].name`.

> Estava acontecendo, eu avisei o talisson, acredito que tenha corrigido

Acho que podemos descartar esse issue aqui então, certo @matheusgnreis ?

**Comment by matheusgnreis** [comment]
Sim, seria nas etiquetas mesmo. Semana passada tive enviar via transportadora lá pra minha sogra uns pedidos e eles pediram para inserir nome completo pra evitar que entregue para pessoa errada com cep de cidade pequena. Vou fazer um css aqui pra mudar o rótulo, como sugestão de inserir o nome completo. Até olhei alguns pedidos aqui da tia sonia, o cliente recoloca o nome completo lá em destinatário, pelo que consta dentro dos pedidos

**Comment by leomp12** [comment]
CSS não sô, só mudar no componente aqui então...
