### ISSUE TITLE
Deixar selecionado por padrão a opção de frete mais barato

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#280]
**Is your feature request related to a problem? Please describe.**

Quando existe mais de 1 opção de frete, não tem critério para definir qual ficará selecionado por default.

**Describe the solution you'd like**

Criar uma opção para definir que o frete 'mais barato' fique selecionado por default.

**Describe alternatives you've considered**

**Additional context**

Sugestão retirada da comunidade: [Clique Aqui!](https://community.e-com.plus/t/selecao-de-frete-automatica/565/2)
![exemplo_funcionamento](https://user-images.githubusercontent.com/60987858/89221913-79a16b80-d5aa-11ea-817f-528fc04747f5.png)

**Comment by leomp12** [comment]
@ThaisChaves vou passar a selecionar o mais barato por padrão, por enquanto vou manter sem seleção manual, já resolve?

**Comment by ThaisChaves** [comment]
Resolve sim Leo!

**Comment by leomp12** [comment]
@ThaisChaves como explicado no commit que fechou o issue, agora vai ordenar por preço e se o preço for igual vai ordenar por prazo, sempre o menor primeiro, também vai selecionar o mais barato porque por padrão começa selecionando a primeira opção.
Isto sái no próximo release a atualiza em todas as lojas amanhã de manhã :wink:
