### ISSUE TITLE
Criar opção manual para escolher ordem do frete na tela para usuário

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#282]
**Is your feature request related to a problem? Please describe.**
Criar opção para que o lojista escolha manualmente a ordem do frete a ser mostrada.
Hoje esta listando o frete pela ordem do mais barato. Caso hajam preços iguais, ele trás primeiro o com menor prazo de entrega.

**Describe the solution you'd like**
Criar uma opção para que o lojista defina a ordem do frete que ele quer mostrar para o usuário. Isso, porque existem lojistas que possuem o "retirar na loja", mas eles não querem que essa seja a primeira opção a ser mostrada. 

**Describe alternatives you've considered**

**Additional context**
Sugestão retirada do tópico da comunidade [Veja aqui!](https://community.e-com.plus/t/selecao-de-frete-automatica/565/8)

**Comment by matheusgnreis** [comment]
No caso, @leomp12 é aquilo que havia informado, ter uma pré-seleção do mais barato, para alguns funciona bem, mas para outros isso é um problema. Talvez melhor que uma ordem, talvez seja um modalidade permitir escolha e outro ter uma pré-seleção automática. Além do Loja Lov, a Voller reclamou disso no manual e o Bela Virtuosa também, pois o cliente ele quer escolher uma forma de envio, ou mesmo mudar para uma outra. Se for automático, ele as vezes ou passa batido compra e depois reclama com lojista ou vai ficar rodando até encontrar ou desistir.

**Comment by leomp12** [comment]
@matheusgnreis sao coisas diferentes na verdade, aqui estamos falando de ordenacao, nao de selecao. Alem disto no mobile nao esta pulando mais o step de shipping, mesmo que selecionado.

> O Voller deveria criar as regras de envio corretamente para a que a opcao respectiva a regiao do Bras apareca apenas para a respectiva regiao.

**Comment by matheusgnreis** [comment]
Na verdade @leomp12 o problema é o mesmo pelo relato do cliente, só proposição de solução distintas. Ele relata que pelo cliente não ter que selecionar o frete, ele acaba clicando em finalizar e somente depois vê que fechou a compra com retirada na loja. A sugestão era ele colocar uma ordem em que o frete grátis não ficasse como primeira opção, uma que ele desejasse e assim o cliente veria o valor do frete impactando na compra dele e talvez se preocuparia em olhar o frete. Se a opção fosse passível de escolha, o cliente iria tomar o ato de escolher de uma forma ou de outra. Mas o que a Thaís informou é uma medida que funciona para resolver, uma vez que o frete grátis nunca sera primeira opção.

**Comment by leomp12** [comment]
Nao vou forcar uma ordem colocando o frete gratis como segunda opcao, vou permitir que o lojista orderne as formas de envio manualmente, como eh feito para formas de pagamento. A forma de envio eh selecionada automaticamente para agilizar o checkout, se passarmos propositalmente a selecionar por padrao uma forma de envio pior (nao gratis) perde totalmente o sentido.
Qualquer coisa depois pode ser implementado uma opcao para nao selecionar automaticamente a forma de envio.

**Comment by leomp12** [comment]
@ThaisChaves à exemplo da ordenação de formas de pagamento, as formas de envio podem ser ordenadas pelo ID do app na variável global `window.ecomShippingApps`, ex.:

```js
window.ecomShippingApps = [ 1248 ]
```

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/f21d7e5bb625ee99ecbd1693825a7ddcdd88b906

**Comment by ThaisChaves** [comment]
Ok👍
Vou fazer e repasso para o logista.

Em seg, 10 de ago de 2020 20:40, Leonardo Matos <notifications@github.com>
escreveu:
