### ISSUE TITLE
Criar filtro para produtos visíveis / não visíveis no painel administrativo

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#286]
**Is your feature request related to a problem? Please describe.**
Não é possível filtrar produtos visíveis/ não visíveis no painel administrativo.

**Describe the solution you'd like**
Adicionar no painel administrativo, na exibição de todos os produtos, filtro por produtos visíveis ou não visíveis na loja.

**Describe alternatives you've considered**

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/sugestao-filtro-para-produtos-visiveis-nao-visiveis-na-loja/599).

**Comment by leomp12** [comment]
@ThaisChaves na verdade isso não é um issue do Storefront, pelo que entendi seria para o https://github.com/ecomplus/admin

**Comment by ThaisChaves** [comment]
Ok. Abri lá onde orientou.
