### ISSUE TITLE
Quantity selector grid component

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/storefront#287]
**Describe the solution you'd like**

The option to create a product with options where the user can select units number of each option. The store owner could limit the number of units, to a max, min or exact amount. [This](https://www.duasxicaras.com.br/Kit-10-Caixas-de-Capsulas-Produto-Unico ) is a example of how it should work.

**Comment by leomp12** [comment]
@vitorrgg na verdade não precisamos "criar um produto", precisamos de um Vue component (`QuantitySelector` :thinking: ) que receba item(s) (produtos ou variações) em prop e renderize seletor(es) de quantidade com opcionais (outras props) quantidades mínima e máxima.

**Comment by leomp12** [comment]
@vitorrgg se precisarmos criar um produto diferente é um issue do  https://github.com/ecomplus/admin , mas acho que não é o caso, podemos só criar este componente e neste exemplo o lojista cria kits no _Descontos e campanhas_ e usamos o componente setando min e max com o número do itens do kit, parece que resolve?

**Comment by vitorrgg** [comment]
Acredito resolver sim.
