### ISSUE TITLE
Customizable product. 

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/storefront#288]
Some users and leads require the feature of a customizable pruduct. A product where buyers could enter with texts, and files to customize what they're buying. [This](https://www.ivocamisas.com.br/camisa-everton-i-20-21) is a example of how it should work with texts, and [here](https://www.querocase.com.br/you-art-fundo-banana039s) we can see one with files.

**Comment by leomp12** [comment]
Duplicado, ainda dependente da implementação no admin primeiro:
https://github.com/ecomplus/storefront/issues/225
