### ISSUE TITLE
Exibir preços e permitir compras apenas para usuários cadastrados

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/storefront#294]
**Is your feature request related to a problem? Please describe.**

Algumas lojas que trabalham com atacado vendem exclusivamente para PJs. Nesse caso ferramentas de descontos progressivo não atendem essa necessidade.

**Describe the solution you'd like**

A solução seria uma opção de setar que estes preços só sejam exibidos para usuários logados com CNPJ.

**Comment by leomp12** [comment]
@vitorrgg acho que seria exibir o preço só para usuário logados, não? Não verificamos o tipo de registro neste ponto, se a venda é feita apenas B2B o formulário de cadastro é que deve aceitar apenas PJ.

**Comment by leomp12** [comment]
Pra isto acho que temos que implementar:
- Campo (Boolean) no CMS para exibir preços apenas a usuários logados;
- Preços não devem ser pre-renderizanos no EJS quando esta propriedade for setada;
- Prop nos componentes `TheProduct` e `ProductCard` para exibir preços apenas com usuários logados, se true checar login com o `ecomPassport`;

**Comment by vitorrgg** [comment]
Isso, seria apenas para PJ. 

Tive uma conversa ontem com o usuário que fez essa solicitação, ele disse que após validar esse modelo, gostaria de aprovar os usuários. Então o preço seria apenas para usuários PJ aprovados. Já mencionando para não ter algum retrabalho caso o desenvolvimento seja muito diferente.

**Comment by leomp12** [comment]
@vitorrgg o que eu disse é que este issue não envolve ser PJ ou não, aceitar apenas PJ e mostrar preços apenas para usuários logados são features diferentes.
Bloquear cadastro de PF é fácil, mas é outra feature, outro issue, o que eu descrevi sobre a implementação é para mostrar preços a usuários logados, independente do tipo de cadastro, não faz sentido verificar o tipo de cadastro neste ponto...

**Comment by leomp12** [comment]
> Eu entendi que o lojista em questão aceita apenas PJ, só "traduzi" seu issue (sobre mostrar os preços) linkando as implementações necessárias.

**Comment by vitorrgg** [comment]
Creio que é melhor seguir nesse issue com a questão do _Kanto do artista_ do que criar um novo, correto @leomp12 ? A diferença seria um feature a mais que seria a possibilidade do cliente para ver os preços terem que ser aprovados por um adm da loja.
