### ISSUE TITLE
Incluir paymentAppsSort para a tela de produto para organizar formas de pagamento.

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#295]
**Is your feature request related to a problem? Please describe.**
Na tela de opções de pagamento no produto, as formas de pagamento são mostradas aleatoriamente. O Lojista precisa de uma ordem, assim como já existe durante o fechamento da compra.

**Describe the solution you'd like**
Na tela do produto, trazer a paymentAppsSort

**Describe alternatives you've considered**

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/fixar-formas-de-pagamento/309/17).

**Comment by leomp12** [comment]
@ThaisChaves na verdade a mesma variável é considerada na página de produto ([aqui](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-components/src/js/TheProduct.js#L98)) e checkout, mas na verdade a variável é `window.ecomPaymentApps`, `paymentAppsSort` é o nome da prop do componente `TheProduct`...

**Comment by leomp12** [comment]
Em qual loja isto não funcionou? Você já verificou como está o `window.ecomPaymentApps` nesta loja?

**Comment by ThaisChaves** [comment]
Oi @leomp12  . Foi na lov.
Se estou no carrinho de compras, ele retorna, mas se estou na tela do produto, ele não retorna:

**Tela do produto:**

![tela_carrinho](https://user-images.githubusercontent.com/60987858/90550350-375d5a00-e166-11ea-822a-6a3516a7e44e.png)


**No carrinho:**

![carrinho](https://user-images.githubusercontent.com/60987858/90550306-26ace400-e166-11ea-90ef-1addaae32846.png)

**Comment by leomp12** [comment]
@ThaisChaves então a variável está configurada só no checkout, não é um erro da página de produto, a questão é que se desejamos aplicar a ordenação em toda a loja a variável `window.ecomPaymentApps` deve ser setada em toda a loja.

**Comment by leomp12** [comment]
Não sei onde ele adicionou o trecho de código setando o `ecomPaymentApps`, provavelmente adicionou em um script importado apenas no checkout, em vez disto sugiro que ele adicione no CMS (pra facilitar) antes de `</head>`.

**Comment by leomp12** [comment]
Antes de /head:

```html
<script>window.ecomPaymentApps = [/* os ids aqui */]</script>
```

**Comment by ThaisChaves** [comment]
Ok.
Vou pedir para ele verificar! Obrigada!
