### ISSUE TITLE
Sugestão de criar slider de banners na categoria

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#298]
**Is your feature request related to a problem? Please describe.**
No cadastro da coleção tem a possibilidade de colocar mais de um banner, mas somente um é mostrado na tela da loja.

No CMS : **Layout** > **Páginas** > **Coleção** é tem a opção para habilitar para mostrar banner da coleção.

**Describe the solution you'd like**
Criar opção para habilitar Slider de banner, onde quando houver mais de um banner na coleção, ele deve agir como slider.(respeitando os mesmos segundos que estão configurados no CMS para o banner inicial).

**Describe alternatives you've considered**
Caso a opção de **habilitar slider** não esteja marcado, mostrar os banners em sequencia. Se tiver 2 banner, mostrar os 2. Hoje esta mostrando somente 1 banner, mesmo existindo mais no cadastro da coleção.

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/icone-e-banners-nas-colecoes/642).

**Comment by leomp12** [comment]
Batendo o olho no issue, acho que só é necessário (resumindo) editar um pouquinho o `document-banner.ejs` para possivelmente incluir o `banner-slider.ejs` :cake:
