### ISSUE TITLE
Criar opção para ordenar produtos na loja por 'lançamento'

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#301]
**Is your feature request related to a problem? Please describe.**
Na loja online, quando buscamos por algum produto ou acessamos alguma categoria, na parte de ordenar tem: Menor preço / maior preço/ relevância / vendas. Não tem como incluir a opção: **Lançamento**.

**Describe the solution you'd like**
Incluir o filtro **lançamento** e trazer ele como primeira opção e passível de escolha

**Describe alternatives you've considered**

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/ordenar-produtos-na-loja-online/656).

**Comment by leomp12** [comment]
Batendo o olho no issue, acho que só é necessário (resumindo) editar um pouquinho o `document-banner.ejs` para possivelmente incluir o `banner-slider.ejs` :cake:
