### ISSUE TITLE
Sugestão de mostrar na página inicial no produto o valor parcelado

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#303]
**Is your feature request related to a problem? Please describe.**
Na página inicial embaixo de cada produtos mostrar o valor em parcelas do **pagamento personalizado**

EXEMPLO:

CHOKER WITCH’S HAT
R$ 25,00
5X DE R$ 5,00 SEM JUROS
R$ 23,75 NO DEPÓSITO EM CONTA OU PICPAY

**Describe the solution you'd like**
Mostrar na vitrine o desconto da forma de pagamento personalizada

**Describe alternatives you've considered**

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/formas-de-pagamento-pagina-inicial/663).

**Comment by leomp12** [comment]
Se entendi direito isso ja existe a bastante tempo, nas vitrines ja mostramos o valor parcelado e com desconto, a depender sempre dos aplicativos de pagamento que estao sendo usados e as respectivas configuracoes...

Na demo, por exemplo:

![Screenshot_2020-08-29 My Shop](https://user-images.githubusercontent.com/10326572/91646354-98b5e080-ea24-11ea-98df-39df896b3993.png)

**Comment by leomp12** [comment]
@ThaisChaves por enquanto vou fechar o issue, se eu tiver entendido errado voce pode abrir novamente e tentar dar mais detalhes da sugestao de implementacao por favor...
