### ISSUE TITLE
CMS insert code preview

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#305]
**Is your feature request related to a problem? Please describe.**
Every change on CSS/HTML via CMS insert code page can be seen only after a new deploy, specially for CSS changes it's so much annoying and may trigger lot of unnecessary deploys.

**Describe the solution you'd like**
Render a template preview for _Layout > Insert Code_, it may be easier then pages preview as it doesn't have sections d&d and no need to work with EJS (although it can be used too). Render component may get home HTML and add/replace code on `</head>` and `</body>` dynamically.

**Describe alternatives you've considered**
N/A

**Additional context**
A little related to https://github.com/ecomplus/storefront/issues/172

**Comment by talissonf** [comment]
https://github.com/ecomplus/storefront/pull/316
