### ISSUE TITLE
Widget for Google Analytics

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#306]
**Is your feature request related to a problem? Please describe.**
Some merchants wants an simpler integration with GA (pageviews and purchase only) in place of enhanced eCommerce integration with GTM.

**Describe the solution you'd like**
Create a new widget for GA direct integration sending normal page view events, additional page views for checkout SPA and purchase event only.

**Describe alternatives you've considered**
Ask the merchant to learn enhanced eCommerce and use GTM widget properly :stuck_out_tongue: 

**Additional context**
https://community.e-com.plus/t/configurando-analytics-via-tag-manager-com-acompanhamento-de-e-commerce/132/15

**Comment by leomp12** [comment]
@ThaisChaves ou @matheusgnreis alguém pode dar um toque no lojista amanhã por favor? Acho que não é necessário testar, mas se quiserem...

**Comment by ThaisChaves** [comment]
oi. Já passei para o lojista!
