### ISSUE TITLE
Create option to choose the order of the product list

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#314]
**Is your feature request related to a problem? Please describe.**
The standard order of products is sales. The shopkeeper wants to define "launches".

**Describe the solution you'd like**
Create option to choose the order of the product list.

**Describe alternatives you've considered**

**Additional context**
![ordenacao](https://user-images.githubusercontent.com/60987858/93126335-94372c00-f6a2-11ea-9ce8-777a84afc30e.png)
[sugestão retirada da comunidade](https://community.e-com.plus/t/ordenacao-padrao-lancamento-nas-categorias/744)

**Comment by matheusgnreis** [comment]
Sugiro colocar no CMS dentro de coleções, categorias, marcas e pesquisas uma seleção onde, o lojista pudesse selecionar lançamentos, ou outra opção e a partir dessa escolha ela representar na loja

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/9f280afe56064ce1a608653994e07b68e5e76bed
