### ISSUE TITLE
Implementação storefront não repassada para lojas

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#317]
**Descreva o erro**
Vemos que no storefront-template em https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/pages/%40/layout/header.ejs#L16 existe um modelo para buscar o cor de fundo no cms e colocar no stripe lá, mas aqui nao tem https://github.com/ecomplus-stores/adequim-loja/blob/master/template/pages/%40/layout/header.ejs, teve loja que copiei o header.ejs do storefront-template e colei lá para dar certo, qualquer coisa faço isso nessa loja também

**Comment by matheusgnreis** [comment]
Ajustei nessa loja de cima, mas um exemplo de loja nova que nao tem isso é https://github.com/ecomplus-stores/ravenous/blob/master/template/pages/%40/layout/header.ejs

**Comment by leomp12** [comment]
É porque pra usar Git subtree tive que criar outro repo pras views aqui https://github.com/ecomplus/storefront-starter-views .
Tava desatualizado mesmo, tô publicando agora e vai atualizar as lojas todas automaticamente.
