### ISSUE TITLE
Ordenação na estante de produtos não esta funcionando

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#323]
**Describe the bug**
No CMS, incluo uma estante de produtos e defino a **ordenação**. Ela não esta sendo respeitada.

**To Reproduce**
1. Acesso o CMS e incluo uma estante de produtos.
2. Defino uma coleção qualquer.
3. No campo ordenação, coloco por exemplo **Menor Preço**.
4. A estante não esta respeitando o Menor preço. Ele mostra 1º o item com o menor preço, mas os demais não segue a ordem crescente.

**Screenshots**
![menorpreco](https://user-images.githubusercontent.com/60987858/94055935-f9ca9d00-fdb3-11ea-9f7a-50b7e68c8c6c.png)
![Itens](https://user-images.githubusercontent.com/60987858/94055953-fe8f5100-fdb3-11ea-8d72-35bd8a7aca9d.png)

**Desktop (please complete the following information):**
Utilizei guia anônima para abrir o site e ver a ordenação que seria mostrada. Também limpei cache.

**Additional context**
Retirado da [comunidade](https://community.e-com.plus/t/ordenacao-nas-estantes-de-produtos/777).

**Comment by leomp12** [comment]
Na verdade ele está pegando os 24 produtos com menor valor da respectiva coleção, mas depois está embaralhando porque a opção _Embaralhar produtos_ está ativa.
Ou seja, se tiver mais de 24 produtos, nesta configuração sempre serão escolhidos os 24 mais baratos, mas não necessariamente o mais barato aparecerá primeiro porque estes 24 serão sortidos, pra ficar sempre na ordem exata basta clicar no switch e desativar esta opção.

**Comment by leomp12** [comment]
@ThaisChaves se minha explicação for suficiente dá um toque no lojista e fecha o issue aqui por favor :+1:

**Comment by ThaisChaves** [comment]
Entendido!! :smile:
