### ISSUE TITLE
Sugestão de criar opção para listar produtos por ordem alfabética

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#330]
**Is your feature request related to a problem? Please describe.**
O lojista possui necessidade de que os produtos venha ordenado de forma alfabética. Para por exemplo vir todas as blusas, depois calças ...

**Describe the solution you'd like**
Criar opção para listar itens por ordem alfabética.

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/ordenar-produtos-por-ordem-alfabetica/857/4).

**Comment by matheusgnreis** [comment]
@leomp12 um lojista está perguntando se tem alguma expectativa de quando vai sair

**Comment by leomp12** [comment]
Ordernar pelo nome especificamente é mais lento porque o `name` é um campo text do ELS, vou adicionar pelo `slug` que é um keyword e quase sempre é respectivo (ou deveria) ao nome.
