### ISSUE TITLE
Error com picture tag em Safari

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#342]
Quando existem imagens com webp no macbook, ele acaba buscando a imagem mobile e ai está ficando desformatado. Por ser uma imagem mais vertical do que horizontal, fiz teste em 3 lojas. A customic por exemplo ela fica em um tamanho até ok na tela, mas passador de slide tanto lateral, quanto ao final estão no meio dos produtos
![customic-mac](https://user-images.githubusercontent.com/35343551/96643640-41ced800-12fe-11eb-8090-9194b989c9e7.png)

No caso da loja lov, ela nao tem a imagem respectiva pra png, vou até avisa-la e fica em branco mas com as marcações lá em baixo:

![lojalov-mac](https://user-images.githubusercontent.com/35343551/96643717-5ad78900-12fe-11eb-85d0-7e51e31cef31.png)

No linden com a imagem é enorme (800x900 no mobile), já vou falar pra diminuir fica esse trein estranho:

![lindenleaves-mac](https://user-images.githubusercontent.com/35343551/96643792-7b074800-12fe-11eb-9ec7-786801d63ad6.png)

**Comment by leomp12** [comment]
@matheusgnreis põe aqui os URLs das imagens que estão sendo carregadas em uma das lojas por favor

**Comment by leomp12** [comment]
Não tenho certeza se isso é por causa do WebP ou por causa da `<picture>`, isso é só a bomba do Safari né?

**Comment by matheusgnreis** [comment]
Só deu esse erro quando tinha webp

**Comment by matheusgnreis** [comment]
Depois vou tentar colocando na mesma loja webp e png em banners diferentes para testar

**Comment by leomp12** [comment]
@matheusgnreis ok, só lembra de colar aqui os URLs desses banners que foram carregados por favor, se pá inspeciona elemento e cola os trechos de HTML também...

**Comment by matheusgnreis** [comment]
https://www.lindenleaves.com.br/img/uploads/banner-com-escrita-ate-30-off-em-todo-site-e-frete-gratis-para-regiao-sul-e-sudeste-nas-compras-acima-de-r-300-00-ao-fundo-aparecendo-os-oleos-corporais-memories-lov-again-pick-me-up.-2-1-.jpg

https://customic.com.br/img/uploads/Banners-Mobile-II-A.png

https://www.lojalov.com.br/img/uploads/frete_gratis_mobile.webp

**Comment by leomp12** [comment]
Pois é, do Customic mesmo não é WebP, negócio é a `<picture>` tag, pelo jeito o Safari faz a proeza de não respeitar media query nela.

**Comment by matheusgnreis** [comment]
O problema é webp mesmo conforme eu tinha visto, no desktop não está tendo aquela troca para jpg. Fiz um teste rápido, onde o lojista tem um banner jpg equivalente ao webp, só que ele continua pegando a versão mobile que é jpg, quando não tem, ocorre o que mostra na loja do Loja Lov fica aquele bloco grande. Na loja da customic, talvez tenha sido algo relacionado ao meu navegador, pois depois que tinha visualizado isso na loja lov, testei na customic e mostrou parecido, mas pode ter sido cache, sei la, safari tem esses problemas, agora não mostra mais. No linden leaves, eu modifiquei no local, troquei no bloco webp por jpg e tive o resultado 


![Captura de Tela 2020-10-28 às 13 04 57](https://user-images.githubusercontent.com/35343551/97464219-625ee980-191f-11eb-9aa7-a078bed8a4d3.png)

Ou seja, mostrando certinho

**Comment by leomp12** [comment]
De qualquer forma acho que não tem muito o que fazer no Storefront, é uma limitação do navegador, se for WebP menos mal, neste caso deve-se usar WebP tanto pra mobile quanto desktop, com fallbacks em PNG pra ambos também.
Se for limitação do Safari com a `<picture>` tag não vejo como contornar, só se for com gambiarra em JavaScript em cima...

**Comment by leomp12** [comment]
> O problema é webp mesmo conforme eu tinha visto, no desktop não está tendo aquela troca para jpg

Reparei nisso agora, na verdade o fallback pros banners nunca foi com JPG @matheusgnreis , nos banners sempre foi apenas com `.png`, basicamente tenta substituir a extensão `.webp` por `.png`, portanto seriam dois arquivos pra cada banner, um `.webp` e outro `.png`, com exatamente o mesmo filename mudando apenas a extensão.

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/lib/utils.js#L10-L17

Se eles estavam usando `.jpg` (parece ser o caso porque agora mesmo estão imagens JPEG) não funcionaria mesmo.

**Comment by matheusgnreis** [comment]
Vou fazer um teste, colocando png no safari pra rodar. Amanhã vou mexer na loja deles e já vejo isso

**Comment by matheusgnreis** [comment]
Eu até mandei retirar o webp, pra não ter o problema. Depois aconselhei colocar png, vou ver em que pé está.

**Comment by leomp12** [comment]
Tirar WebP não pô :no_good_man:

**Comment by matheusgnreis** [comment]
Vou fechar, png com webp no teste que fiz funcionou!
