### ISSUE TITLE
Criar um parâmetro no CMS, onde o lojista possa ordernar paginas

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#343]
Essa sugestão já apareceu algumas vezes na comunidade, onde o lojista quer que na categoria apareça sempre os produtos mais recentes primeiro, ou seja, se for possível criar uma parâmetro, onde na página de categorias (principalmente), coleções e afins seja possível o lojista setar qual ordenamento quer.

**Comment by matheusgnreis** [comment]
Esse de ordem alfabetico por exemplo seria mais uma opção https://github.com/ecomplus/storefront/issues/330

**Comment by matheusgnreis** [comment]
@leomp12

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/issues/314
