### ISSUE TITLE
Sugestão de criar parâmetro para filtro da pesquisa

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#362]
**Is your feature request related to a problem? Please describe.**
Usuário faz a pesquisa do filtro do tamanho G por exemplo. Ele precisa de um link que quando for acessado, já traga esse filtro.

**Describe the solution you'd like**
Criar parâmetro de URL

**Additional context**
Sugestão da [comunidade](https://community.e-com.plus/t/link-filtro-por-tamanho/1031).

**Comment by leomp12** [comment]
@ThaisChaves ficou no formato `?filters[]=${grid_id}:${option}`, neste exemplo do tamanho pode ser `?filters[]=size:G` ou `?filters[]=tamanhos:G` (a depender das grades da loja).
É possível setar mais de um repetindo o parâmetro como `?filters[]=size:G&filters[]=colors:Azul`
