### ISSUE TITLE
Erro com Brinde ao diminuir valor

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#365]
**Descrever bug**
Na loja https://www.fishingco.com.br/ o brinde é para valor mínimo de 300. Quando insiro o valor, os brindes aparecem, mas quando reduzo a valor menor do que 300,00 continua aparecendo a tag brinde, porém como deveria ser soma-se ao carrinho. Para não ficar incongruente, seria interessante retirar a tag de brinde, se não o cliente fica vendo a tag com valor cortado e do outro lado se soma

**Para reproduzir**
1 - Elevar carrinho para acima de 300,00
2- Diminuir carrinho para abaixo de 300,00

**Screenshots**
![brinde](https://user-images.githubusercontent.com/35343551/99962296-b6b68700-2d6e-11eb-9806-5fe14844f525.png)

**Comment by matheusgnreis** [comment]
@leomp12

**Comment by leomp12** [comment]
@matheusgnreis nos testes que fiz, com essa mesma loja inclusive, tem funcionado, vê se consegue encontrar um erro no console por favor ou debugar as requests no `apply_discount` nestes casos.

**Comment by matheusgnreis** [comment]
Isso deve acontecer só quando tem variação, pedi para retirar, duplicar os produtos e considerar como simples apenas, testando com simples funciona perfeitamente
