### ISSUE TITLE
Erro para mostrar forma de pagamento no carrinho

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#366]
No carrinho, mostra as formas de pagamento abaixo do total da compra, nele mostra o valor a ser pago no boleto e cartão, porém o desconto que é considerado na forma de pagamento, pega o valor total do pedido e não o que foi configurado, conforme no print:

![discount-paghiper](https://user-images.githubusercontent.com/35343551/99995174-c5b22f00-2d98-11eb-9ee2-0cb634e0db6f.png)

Na loja que deu isso, eu vou trocar o valor, o valor pago no boleto, pelo % de desconto.

**Comment by leomp12** [comment]
Estranho, consegue testar isso na 1011 e colocar aqui por favor? Principalmente o corpo da request em `apply_discount.json`.

**Comment by matheusgnreis** [comment]
Sim, vou verificar já

**Comment by matheusgnreis** [comment]
Coloquei lá, o desconto é aplicado no valor total da compra sempre, só muda quando clica lá na forma de pagamento boleto, acredito que o ```apply_discount.json``` não vai mostrar isso, seria o list_payments, não? Vou colocar ambos:

{"meta":{"domain":"storefront-demo.e-com.plus","lang":"pt_br","utm":{},"amount":{"subtotal":1000,"freight":41.09,"discount":0,"total":1041.09},"items":[{"name":"TV LG UHD 55” Q6FN - Tizen Conversor Digital Modo Ambiente Linha 2018","sku":"ZFA2236","price":1000,"quantity":1,"currency_id":"BRL","currency_symbol":"R$","product_id":"5cdf0e8f887ef430f1f6d0a7","final_price":1000}],"customer":{"_id":"5cb8ea90887ef430f1f66c89","display_name":"Matheus"},"currency_id":"BRL","currency_symbol":"R$","channel_type":"ecommerce"},"result":[{"_id":"5f5fbd767430f92180ef76fe","app_id":1252,"took":34,"version":"1.7.0","validated":true,"response_errors":null,"error":false,"error_message":null,"response":{}}]}

E o list_payments para o paghiper

```
{"_id":"5fbc523e69274c73fcda6913","app_id":1251,"took":45,"version":"1.0.2","validated":true,"response_errors":null,"error":false,"error_message":null,"response":{"payment_gateways":[{"label":"Boleto bancário - Paghiper","payment_method":{"code":"banking_billet","name":"Boleto bancário - PagHiper"},"intermediator":{"name":"PagHiper","link":"https://www.paghiper.com/","code":"paghiper"},"discount":{"type":"percentage","value":7.14,"apply_at":"subtotal"},"type":"payment","fetch_when_selected":false}],"discount_option":{"label":"Boleto bancário - Paghiper","value":7.14,"type":"percentage"}}}
```

**Comment by leomp12** [comment]
Na real eu viajei, o ponto deve ser o corpo da requisição no
`list_payments`, mas se já está configurado du faço uns testes lá

Em seg, 23 de nov de 2020 21:33, Matheus Reis <notifications@github.com>
escreveu:
