### ISSUE TITLE
Suportar kit com variações

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#370]
**Describe the bug**
Ao finalizar a venda com produto Kit composto por variação, ele considera o valor do produto individual e não o preço do KIT.

**To Reproduce**
1. Cadastre um KIT que seja composto por um produto com variação:
![Screenshot - 2020-11-30T155449 061 (1)](https://user-images.githubusercontent.com/60987858/100651813-cdd41680-3324-11eb-8057-8e887a4b60a8.png)

1. Ao vender o produto, veja que o carrinho comporta corretamente, assumindo o valor do Kit:
![Screenshot - 2020-11-30T155255 918](https://user-images.githubusercontent.com/60987858/100651888-ec3a1200-3324-11eb-845e-402730a13a77.png)

1. Porém, ao finalizar a venda, ele desconsidera o valor do KIT e finaliza com o valor do próprio produto.
![Screenshot - 2020-11-30T155423 239](https://user-images.githubusercontent.com/60987858/100651860-e0e6e680-3324-11eb-8473-b8ed2084fcb7.png)

**Additional context**
. Produto para simular: https://storefront-baby.netlify.app/kit-leve-10-pague-9-esmalte-cores-vibrantes
. Cadastro do produto KIT: https://app.e-com.plus/#/resources/products/5fbf8c3069274c73fcdc3569

**Comment by leomp12** [comment]
Uai @ThaisChaves , mas você colocou a quantidade do item como `0`, zero é diferente de ficar em branco (varíavel), zero é sempre zero mesmo...

**Comment by ThaisChaves** [comment]
@leomp12 , eu coloquei 0 depois de alguns testes. Se deixar em branco, da o mesmo problema.(mudei e deixei em branco pra vc dar uma olhada).
E mesmo que esteja zero, ele não poderia mostrar um valor no carrinho e ao fechar a compra mudar o valor. :+1:

**Comment by ThaisChaves** [comment]
@leomp12 ainda tem outro problema. Antes eu só vi que o valor mudava, mas eu não finalizei a venda. Olha o erro que dá quando finaliza:

![erro-finalizar kit](https://user-images.githubusercontent.com/60987858/101472246-1ee89980-3927-11eb-9582-fcc0007c4276.png)

O item esta com a quantidade em branco do kit no cadastro e adicionei ele assim no carrinho pra comprar:
![Screenshot (10)](https://user-images.githubusercontent.com/60987858/101472465-6707bc00-3927-11eb-981e-997ad04fd78e.png)

**Comment by leomp12** [comment]
Beleza @ThaisChaves , na verdade eu nem testei para variação, de fato esse kit por enquanto funciona apenas com produtos simples.

**Comment by matheusgnreis** [comment]
Tem previsão disso, temos uma loja que precisa disso, migrou quando lançou e depois viu que não funcionava para variação, ofereci então voltar pra club e quando tivesse informava novamente, mas quis saber de prazo

**Comment by leomp12** [comment]
Vou tentar fazer até amanhã @matheusgnreis , se não até o fim do mês vai sair.

**Comment by leomp12** [comment]
Já funcionando para kits com quantidades dinâmicas como o do exemplo abaixo:

![Screenshot_2021-01-14 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/104657788-5f62d200-56a0-11eb-8906-a4aca76b25dd.png)
![Screenshot_2021-01-14 E-Com Plus Dashboard App(1)](https://user-images.githubusercontent.com/10326572/104657791-612c9580-56a0-11eb-886f-bd18cc37278d.png)

Nesse caso o segundo produto tem variações:

![Screenshot_2021-01-14 My Shop](https://user-images.githubusercontent.com/10326572/104657892-8d481680-56a0-11eb-8503-65e33af947bd.png)

Para kits com composição de quantidades fixas por item é necessário implementar no admin primeiro (exibir as variações uma por uma no admin).
