### ISSUE TITLE
Opcionalmente iniciar a primeira forma de pagamento aberta

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#379]
**Is your feature request related to a problem? Please describe.**
Hoje o lojista consegue organizar a ordem a ser exibida das formas de pagamento. Ele precisa que a opção do mercado pago, além de ser a primeira na lista, já mostre aberta com as opções.

**Describe the solution you'd like**
Criar opção para mercado pago já vir aberto na tela.

**Additional context**
Sugestão retirada da [comunidade](https://community.e-com.plus/t/exibir-meio-de-pagamento-pre-selecionado/870).

**Comment by leomp12** [comment]
@ThaisChaves só pra constar, na verdade isso seria pra qualquer forma de pagamento, o MP é só o caso específico do lojista em questão.

**Comment by leomp12** [comment]
À exemplo do #239, dá pra mockar com JS, ex:

```js
window.ecomDefaultPaymentApp = 1250
```

Falta adicionar ao CMS.

**Comment by ThaisChaves** [comment]
@leomp12 , isso da ordem da forma de pagamento, já funciona.
O que ele quer é que já mostre aberta a tela do mercado pago. Hoje ele precisa clicar para escolher e abrir a forma de pagamento.

Ai a sugestão é que tenha a lista das formas de pagamento e o mercado pago venha aberto.

**Comment by leomp12** [comment]
Sim @ThaisChaves , só mencionei o outro issue porque a implementação é parecida.
Note que a variável é diferente e no outro caso o valor era um array, aqui o valor é um número apenas, o ID do app respectivo no caso.
Isso vai fazer justamente a forma de pagamento já iniciar aberta.

**Comment by ThaisChaves** [comment]
Ahhh. Eu olhei rápido e não reparei que era outra variável. Vou testar aqui e já sugiro pra ele colocar lá!

Brigadããããão!!
