### ISSUE TITLE
Breadcrumb mostrar categoria completa do produto

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#381]
Sugestão de criar opção de mostrar a categoria completa no breadcrumb do produto.

Atualmente ele mostra a ultima categoria e o nome do produto.

A opção iria mostrar a categoria pai, todas as filhas + nome do produto.

Sugestão da [comunidade](https://community.e-com.plus/t/melhorias-layout-desktop/1067/4).

**Comment by leomp12** [comment]
@ThaisChaves é importante mencionar nesses casos que isso é customizável no EJS também, até porque nem sempre vamos poder implementar todas as solicitações caso contrário o CMS acaba ficando um bixo de 7 cabeças.
Especificamente os breadcrumbs são editáveis em `template/pages/@/sections/breadcrumbs.ejs`.
