### ISSUE TITLE
Voltar a usar o payment_method.name no lugar no label na confirmação do pedido

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#382]
Na finalização do pedido, parou de mostrar o campo configurado na forma de pagamento personalizado.
Veja abaixo como funcionava antes:

![Screenshot (12)](https://user-images.githubusercontent.com/60987858/101545523-22f7d400-3986-11eb-82f0-e998b5ae8d0f.png)

Como haviam clientes usando para informar os dados da transferência bancária, preciso que volte a mostrar. Porque hoje, depois que fecha o pedido, se o cliente não anotou os dados para transferência quando escolheu a forma de pagamento, ele não tem mais a informação para proceder com o pagamento.

**Comment by leomp12** [comment]
Uai, já foi atualizado, até te falei no wpp...

**Comment by leomp12** [comment]
Pelo menos acho que falei :smile:

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/3ba51775b46d8972fcaeab31cf418b6c0652d3aa
