### ISSUE TITLE
Comprar novamente duplica produtos do carrinho

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#383]
Assim que finaliza a compra, tem um botão **comprar novamente**.

Ao acionar: ele deveria gerar um novo pedido com os mesmos itens do pedido, porém, ele duplica o campo *quantidade* os produtos.

Se no pedido original tinha 1, ao comprar novamente, vão 2 para o carrinho.

Veja vídeo: 
https://drive.google.com/file/d/1fJJY9A7USkhQigLOos8ifOjBceVKDOzo/view?usp=sharing

**Comment by matheusgnreis** [comment]
Na verdade já existe um produto no carrinho, então ele apenas adiciona. Quando fiz optei por não resetar e gerar um novo carrinho, pois o cliente pode ter outros produtos no mesmo. Se o cliente entra na loja e fala: Vou comprar as mesmas granolas do mês passado e mais algumas coisas, se clicar só em comprar novamente, vai abrir somente as unidades do pedido.

**Comment by leomp12** [comment]
Isso é um issue conhecido na verdade, dobra mesmo, sempre dobrou :smile:

**Comment by matheusgnreis** [comment]
Se fizer a compra, logo após a outra, dobra. Mas se não for, não dobra. Só testar

**Comment by leomp12** [comment]
> Se fizer a compra, logo após a outra, dobra. Mas se não for, não dobra. Só testar

Sim sim, isso é na confirmação da compra eu digo...
