### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by tiepdotme** [ecomplus/storefront#385]
hi, please help me Leonardo.
"Failed to load resource: the server responded with a status of 403 ()" https://passport.e-com.plus/v1/1199/identify.json
i can't verify my identify with passport of e-com, it's out of mine how way i try to test and find the solution for the ecommerce, please have a check bro. so sad that you denied how the way payment could working, because my country use different currency, please help me verify thanks

**Comment by leomp12** [comment]
Hey, the 403 status only means the customer was not found by specified email address, then you should sign up on Storefront checkout:

![Screenshot_2020-12-11 My Shop](https://user-images.githubusercontent.com/10326572/101912537-a68d0d00-3ba0-11eb-9d39-608755de4a4c.png)

You may set `en_us` (or your local language) and currency at [`content/settings.json`](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/content/settings.json#L13-L14) on your deploy, if you want to use a custom language you may purpose addition [here](https://github.com/ecomplus/i18n/tree/master/src) or just customize your Storefront deploy.

**Comment by leomp12** [comment]
To complete checkout you must have apps installed for shipping and payment, directly on [Store API applications](https://developers.e-com.plus/docs/api/#/store/applications/) resource or from our dashboard at https://app.e-com.plus/#/apps .
We don't have specific apps for your country yet (almost all are BR only), global solution for payment is PayPal, you may use it and configure your account, or you can use _Pagamento personalizado_ (custom payment) and _Frete personalizado_ (custom shipping), and configure it manually.

> If you want to integrate another shipping/payment method (and considering you have Node.js skills), give a try at https://github.com/ecomplus/application-starter , this app https://github.com/ecomplus/app-mandabem may be an example for shipping method, and this https://github.com/ecomplus/app-pagarme for payment, both created from Application Starter.

**Comment by harumuki** [comment]
i'm going to do i18n translate to vietnamese, and looking on it, thanks anyway @leomp12

**Comment by leomp12** [comment]
@harumuki looks great! :+1: 
If you want give a try with https://github.com/ecomplus/application-starter to setup local shipping/payment integrations I'll be happy to help you integrating.

**Comment by leomp12** [comment]
> @tiepdotme I answered two emails you sent me, both can't be delivered (your address seems to not be working), I think I've answered the same questions here, just about uploads you can give a new try now...

**Comment by harumuki** [comment]
@leomp12 thanks you so much, you so great man. i can see it change now, as it working great, it is just i change the language to en_us, when checkout it must enter zip code and check first before it can show up. everything seems working fine, good job. i'm on thinking on translate the i18n, and working on some stuff that could process payment on vietnam, and the delivery app checking via vnpost, our main national delivery system.
