### ISSUE TITLE
Some estrelas trustvox

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#392]
Após descer para carregar mais produtos, as estrelas da trustvox somem, provavelmente na Opinoes Verificadas também.
![artestore-ao-carregar](https://user-images.githubusercontent.com/35343551/102527639-253fe980-407c-11eb-810f-cf2cfd318fb3.png)
![artestore-apos-load-more](https://user-images.githubusercontent.com/35343551/102527646-27a24380-407c-11eb-929d-efb08b07caf8.png)

**Comment by leomp12** [comment]
Isso é conhecido até, na Trustvox tem como resolver (talvez) porque eles têm uma configuração do widget para vitrines dinâmicas, o Opiniões Verificadas não tem.

**Comment by matheusgnreis** [comment]
Só fabi q reclamou e ela usa trustvox

**Comment by leomp12** [comment]
Sim sim, eu até vi, mas sempre foi assim com ambos. Trustvox até diz que tem um negócio lá pra vitrine dinâmica, renderizando os produtos sob demanda e tal, fiz uma implementação aqui pra ver se vai rolar...
OV não tem como mesmo.
