### ISSUE TITLE
Estante composta por oferta não esta respeitando somente promocionais

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#403]
Vários produtos foram colocados em promoção.
O lojista criou no CMS uma estante composta por ofertas: https://github.com/ecomplus-stores/celly/blob/master/content/home.json#L61

Porém, após a promoção encerrar, os produtos que não estão em promoção, continuam sendo mostrados na estante 
![Screenshot - 2021-01-18T192611 729](https://user-images.githubusercontent.com/60987858/104967808-0a39ff80-59c3-11eb-83ca-e7d83f5f2f3f.png)

Deve respeitar o parâmetro de ofertas da estante.

Foi reportado pela [comunidade](https://community.e-com.plus/t/produtos-com-preco-de-promocao/1122/17).

**Comment by leomp12** [comment]
Oi @ThaisChaves ,

Acho que já respondi um caso exatamente igual a esse, talvez tem até outro issue :stuck_out_tongue: 

Não é um filtro, é ordenação (`sort`), portanto a configuração não faz com que só apareçam as ofertas, faz com que as ofertas apareçam primeiro, mas nessa estante está configurado `"shuffle": true` (_Embaralhar_) e aí essa ordenação não será estritamente respeitada.

Nesse caso os itens serão ordenados primeiro por oferta, mas a estante tem limite 12 e ela não tem 12 itens em oferta, portanto alguns itens dessa estante não estarão com preço promocional, por fim ela configurou para embaralhar então pode ser que alguns desses itens sem oferta sejam colocados aleatoriamente antes dos promocionais (embaralhados).

> O padrão do `shuffle` é false, acho que eles marcam para true sem saber exatamente como funciona.
