### ISSUE TITLE
Estante de ofertas não testa a data inicial e final da promoção.

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#404]
Vários produtos foram colocados em promoção.
O lojista criou no CMS uma estante composta por ofertas: https://github.com/ecomplus-stores/celly/blob/master/content/home.json#L61

Porém, após a promoção encerrar, os produtos que não estão em promoção, continuam sendo mostrados na estante

![image](https://user-images.githubusercontent.com/60987858/105085859-239c8380-5a77-11eb-8bcd-9d5967a4d12f.png)

A estante não respeita a data da promoção. Para não ser mostrado mais lá, o usuário precisar entrar no cadastro e tirar a data da promoção manualmente.

Verificar a data para compor a estante.

Tópico retirado da [comunidade](https://community.e-com.plus/t/produtos-com-preco-de-promocao/1122/20)

**Comment by leomp12** [comment]
Na verdade isso não é um issue daqui, seria do https://github.com/ecomplus/search-engine em sua função `.setSortOrder('offers')` , mas como conversamos na call não é uma intenção fixá-lo por agora porque a solução trivial não é performática e deve piorar a experiência...

Vai ser um issue conhecido por algum tempo, se for caso o lojista pode editar esses produtos para remover o preço promocional fora da data.
