### ISSUE TITLE
Erro limite de usos totais do cupom

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#407]
**O erro**
Situações:

1) Quando configuro:

total_usage_limit: 1

O checkout informa que `A promoção não pôde ser aplicada porque já atingiu o limite de usos`

Sendo que nunca foi usado.

2) Quando configuro:

total_usage_limit: 1
usage_limit: 1

O checkout informa que `A promoção não pôde ser aplicada porque já atingiu o limite de usos`

3) Quando configuro:

usage_limit: 1

O checkout confirma o desconto

**Comment by matheusgnreis** [comment]
Erro foi na loja usetrucco

**Comment by matheusgnreis** [comment]
Ele tem mais de 100 cupons assim então esse erro deve ser recente

**Comment by leomp12** [comment]
Não é um erro daqui, seria do @ecomplus/discounts , se conseguir simular o erro na loja demo e especificar o cupom facilita também...

**Comment by leomp12** [comment]
Só pra constar, verifica se as regras de desconto desses cupons não têm rótulos e se realmente não houve uma compra com desconto aplicado com esse mesmo rótulo.
A busca na lista de pedidos é pelo `label`, que por padrão vai ser o texto do cupom em si mas também pode ser especificado pelo lojista.

**Comment by matheusgnreis** [comment]
Não, o erro é aqui. Porque a configuração lá fica certinha no hidden_data. O que coloquei mostra no JSON. O problema é na loja

**Comment by leomp12** [comment]
O Storefront não mostra configuração do hidden data, nem acessa isso inclusive porque é privado.

Essa mensagem de erro por exemplo vem da API de módulos com a resposta do aplicativo, se o `label` de fato não está repetido o app não deveria responder com isso mas sim com o valor do desconto.

Se tem algum erro é lá, o Storefront só mostra o que o app retornou...

**Comment by matheusgnreis** [comment]
O rótulo do desconto é mais importante que código do cupom? Não deveria ser o contrário, porque eu posso ter uma campanha de aniversario e ter 6 cupons diferentes pra ela. Na minha cabeça eu colocaria rótulo igual em todas e mudaria o código do cupom. Para quando eu fosse ver a campanha, eu digitaria o nome dela e dai viria os pedidos com os cupons diversos de acordo com ticket do pedido

**Comment by matheusgnreis** [comment]
Nesse cenário ai está funcionando mesmo, expliquei pra ele lá, pra mudar os rótulos

**Comment by leomp12** [comment]
O limite não vale só pra descontos com cupom, por isso o filtro é pelo
rótulo, então não é uma questão de ser mais ou menos importante.

E esse rótulo não aparece para o cliente, ele pode usar um prefixo
"Aniversário" com o próprio código do cupom na frente por exemplo, só não
pode repetir o rótulo idêntico se pretender limitar usos da regra de
desconto.

O rótulo poderia ficar em branco também, usaria o texto do cupom por padrão
e daria certo...

> De qualquer forma poderia ter uma sugestão de melhoria, mas pra seguir
funcionando em outros tipos de desconto teria que ser algo mais elaborado
do que só considerar o código do cupom em vez do label, e issue não tem
relação com esse repositório e sim com o @ecompus/discounts

Em ter, 26 de jan de 2021 21:01, Matheus Reis <notifications@github.com>
escreveu:
