### ISSUE TITLE
Buscando produtos da categoria incorreta quando o nome é igual

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#408]
Tenho a categoria MENINAS (não tem categoria pai). o slug é meninas
Cadastrei a categoria SALE (Nnão tem categoria pai).
Depois cadastrei uma nova categoria MENINAS que é filha da SALE. o slug é meninas1
O Slug das categorias com o mesmo nome é diferente.

Porém, se entro em SALE > Meninas - Ele ate mostra no navegador o slug correto, mas os produtos são os da categoria MENINAS.

Veja exemplo em: https://storefront-baby.netlify.app Entre na categoria MENINAS e depois em: SALE: MENINAS.

Em SALE - MENINAS, veja que o slug é diferente, mas busca exatamente os mesmos produtos.

Problema retirado da [comunidade](https://community.e-com.plus/t/categorias-nao-exibindo-corretamente-os-produtos/1303/12).

**Comment by leomp12** [comment]
De fato o filtro é pelo nome da categoria, é necessário mudar o nome da categoria filha para "Promoções para meninas" por exemplo (no caso mencionado), se quiser que apareça só "Meninas" no menu pode customizar via CSS ou no próprio HTML.

O issue seria em @ecomplus/search-engine mas isso não vai ser alterado por enquanto, não é viável.

**Comment by ThaisChaves** [comment]
Vlw @leomp12 ! Eu ate imaginei isso, mas o Matheus disse que era erro e pediu pra abrir um issue...

Obrigada!! :smiley:
