### ISSUE TITLE
Sugestão de não mostrar itens sem estoque na estante

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#409]
Criar uma opção para não incluir itens sem estoque na estante.

Sugestão retirada da [comunidade](https://community.e-com.plus/t/produtos-sem-estoque-aparecendo-nas-vitrines/1307).

**Comment by leomp12** [comment]
Os produtos sem estoque serão jogados para o final da estante e não deverão aperecer na primeira visualização se a estante tiver produtos o suficiente.

Se a loja tem poucos SKUs deve utilizar uma só estante na página inicial e sem filtros por categoria, coleção ou marca, talvez seja interessante até que essa estante tenha o limite de itens editado para exibir todos os produtos da loja, nesse caso os sem estoque nunca aparecerão antes dos disponíveis.

> O "padrão" em outras plataformas é SSR, nesse caso os itens são listados para a home em backend a cada novo acesso e antes da renderização do HTML são escolhidos os produtos, é totalmente diferente porque no Storefront nem mesmo há servidor e portanto isso não se aplica, e essa diferença de arquitetura é justamente o que deriva a grau de performance e flexibilidade, muito acima desse "padrão".

>  A solução óbvia seria na hidratação listar novamente todos os itens e substituir, mas isso custaria mais requisições e [CLS](https://web.dev/cls/) em todas as lojas, portanto não é uma implementação que valha a pena, é um issue conhecido mas ainda sem ideia de correção definitiva sem perda de performance, portanto é necessário administrar as estantes para evitar o problema.
