### ISSUE TITLE
Consigo reabrir pedido de produto sem estoque para venda

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#418]
1- Faço o pedido do produto e cancelo depois de finalizar.

2- Depois que o pedido é cancelado, faço outras vendas e o produto fica com estoque zerado.

3- Acesso a minha tela (como cliente) em pedido e clico para reabrir. Ele simplesmente reabre. O Pedido vai para o admin como um pedido pendente normal.

4- Porém, não existe saldo para atender ao pedido que foi reaberto. 

5- Como o lojista não sabe que o pedido foi reaberto, ele acha que a plataforma não esta controlando o estoque, pois permite vender mais que tem no cadastro.

**Comment by leomp12** [comment]
Oi @ThaisChaves , isso é um bug sim, mas o issue já está aberto aqui https://github.com/ecomplus/storefront/issues/326
