### ISSUE TITLE
Se login estiver desabilitado, não deve permitir entrar

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#423]
A propriedade   
`
"login": true
`
Se tiver `false`, não poderia permitir entrar na loja e 

`
"enabled": true,
`
Não poderia permitir ir pro checkout.

Mas como não tem nenhum e nem outro no momento. Talvez impossibilitar de chegar ao checkout já seria o ideal do momento

**Comment by leomp12** [comment]
Fazer sem gambiarra...
Isso deveria ser um enhancement em https://github.com/ecomplus/passport , pra ser seguro tem que ser bloqueios a nível de API.
