### ISSUE TITLE
Estoque de itens do kit não sendo respeitado.

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#427]
**Descreva o erro**
Foi permitido vender com kit quantidade superior ao que havia na loja.

**Pare reproduzir**
O teste realizado, na loja havia apenas 5 unidades e foi criado um kit com 5 unidades do produto, ou seja, apenas 1 kit poderia permanecer no carrinho. 
Coloquei 4 kits, correspondendo a 20 unidades do produto, sendo que havia apenas 5. Ou seja, gerando um déficit de 15 unidades. O pedido foi finalizado e os produtos continuaram com ele

**Comportamento esperado**
Ao ser adicionado no carrinho, checar os produtos do kit com o estoque e se não houver quantidade, ser retirado do mesmo, se possível com um aviso, informando que o estoque para aquela quantidade não existe. Além disse, se não houver produtos que compõem o kit, na página de produto idealmente deveria não permitir compra.

**Comment by matheusgnreis** [comment]
As vezes se no carrinho separar os produtos, já deve funcionar e isso seria bom até pra usabilidade depois, caso quisesse aumentar a quantidade de itens do kit, evitando ter que acessar o produto para acessar mais de um kit

**Comment by leomp12** [comment]
Uai mas o kit já é decomposto no carrinho mesmo...
Em qual produto você testou @matheusgnreis ?

**Comment by matheusgnreis** [comment]
O kit aparece como um produto único no carrinho, como vemos no print:
![image (4)](https://user-images.githubusercontent.com/35343551/109538182-8afa1a00-7a9e-11eb-9c04-bdce6afaf8f8.png)
Já o produto que ocorreu o erro é de uma loja a parte:
ID: 6037d09b9332dd6865de9d74
No histórico de mudança de estoque do produto, mostra lá:

```
    {
      "date_of_change": "2021-03-01T12:17:51.658Z",
      "origin": "Order #603a648c9332dd6865e12f86 (5un)",
      "quantity": 5,
      "_id": "603cdb719332dd6865e29fad"
    },
    {
      "date_of_change": "2021-03-01T12:29:05.966Z",
      "origin": "open #603cddff9332dd6865e2a335 (0un)",
      "quantity": -5,
      "_id": "603cde139332dd6865e2a358"
    },
    {
      "date_of_change": "2021-03-01T12:29:08.964Z",
      "origin": "open #603cddff9332dd6865e2a335 (0un)",
      "quantity": -5,
      "_id": "603cde169332dd6865e2a363"
    },
    {
      "date_of_change": "2021-03-01T12:29:11.963Z",
      "origin": "open #603cddff9332dd6865e2a335 (0un)",
      "quantity": -5,
      "_id": "603cde199332dd6865e2a36c"
    },
    {
      "date_of_change": "2021-03-01T12:29:14.964Z",
      "origin": "open #603cddff9332dd6865e2a335 (0un)",
      "quantity": -5,
      "_id": "603cde1c9332dd6865e2a373"
    }
```
O primeiro é antes do pedido, mostrando que nele tem 5 itens em estoque, dai o pedido 603cddff9332dd6865e2a335 que foi o que eu fiz, tiveram 4 entradas de -5 que são os 4 kits que comprei.

**Comment by leomp12** [comment]
Não uai, esse kit aí que só tem um produto pelo jeito, 2 unidades do mesmo produto.
Pra testar eu ainda preciso do link do produto que você acredita estar errado @matheusgnreis

**Comment by matheusgnreis** [comment]
https://jessimakeacessorios.netlify.app/teste-2

**Comment by ThaisChaves** [comment]
@leomp12 , também fiz esse video aqui: 
https://drive.google.com/file/d/1JytCXIbDPCb8FfsHWBEU9Q3s8Gh39vta/view?usp=sharing

O problema é que ele não testa o saldo do produto antes de fechar a venda e deixa vender quantidade maior que tem no cadastro.

**Comment by leomp12** [comment]
Na verdade ele checa o estoque do item sim, mas quando o kit com quantidade fixa é adicionado duas vezes os items ficam separados mesmo e o estoque está sendo verificado de um a um.
De qualquer forma acho que no link do produto aí deu pra saber o que é...

**Comment by ThaisChaves** [comment]
@leomp12 , tudo bem? 
O problema não é adicionar item a item no carrinho quando adiciona varios kits, mas o estoque dos itens esta menor do que consegui finalizar na compra.

No video que eu coloquei, comprei vários kits no pedido, mas só daria pra comprar o total de 2 KITs (porque cada KIT é composto por 2 unidades de cada produto e o saldo do produto era 5). Sendo assim, daria 2 kits (baixando 4 unidades no cadastro), só que consegui comprar vários KITs. O problema é esse.

**Comment by leomp12** [comment]
Oi @ThaisChaves ,
Mas então, é isso mesmo :smile: 

> Na verdade ele checa o estoque do item sim, mas quando o kit com quantidade fixa é adicionado duas vezes os items ficam separados mesmo e o estoque está sendo verificado de um a um.

Pelo que vi ele tá checando o estoque do item a cada kit justamente porque os itens ficam separados a cada unidade do kit (quando o kit tem quantidade fixa).
Eu só não resolvi ainda porque tô resolvendo outras mil coisas haha

**Comment by leomp12** [comment]
@matheusgnreis @ThaisChaves algum produto em alguma loja fácil pra testar? https://jessimakeacessorios.netlify.app/teste-2 não existe mais.

**Comment by ThaisChaves** [comment]
@leomp12, na loja kids tem esse produto aqui: https://app-dev.e-com.plus/#/resources/products/5fbf8fef69274c73fcdc3830
Ele é o do video. Como que eu faço pra testar lá?
