### ISSUE TITLE
O resultado da pesquisa pela palavra acentuada é diferente da pesquisa sem usar acento

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#428]
**Describe the bug**
A empresa tem produtos cadastrados com a palavra cilios e cílios. Se pesquisar sem a acentuação, mostram 4 produtos. Com acentuação mostram mais de 90.

**Expected behavior**
É possível desconsiderar a acentuação para pesquisa dos produtos? Porque se o produto for cadastrado sem querer sem o acento, e o cliente pesquisar, não vai mostrar os demais.

**Screenshots**
Pesquisa sem o acento:
![Screenshot - 2021-03-02T103834 815](https://user-images.githubusercontent.com/60987858/109669306-bccbb900-7b50-11eb-9e28-a988abdd9bc6.png)

Pesquisa com o acento:
![Screenshot - 2021-03-02T103854 911](https://user-images.githubusercontent.com/60987858/109669339-c2290380-7b50-11eb-8759-7bd16c9c9df7.png)

**Additional context**
Se quiser reproduzir a pesquisa o link [é esse aqui](https://jessimakeacessorios.netlify.app/).

[Retirado da comunidade](https://community.e-com.plus/t/paginacao-do-site/1461/8)

**Comment by leomp12** [comment]
Natural que seja diferente, afinal ela cadastrou produtos com acentos e outros sem acentos, o correto é com o acento nesse caso então todos os produtos deveriam ter _cílios_ com acento no nome, nesse caso quem pesquisasse _cilios_ seria corrigido automaticamente para _cílios_ e retornaria todos os 90 produtos.

Se ela preferir também pode adicionar _cilios_ (sem acento) nas keywords dos produtos, nesse caso a busca por _cilios_ não seria corrigida, em vez disso já retornaria nos resultados os produtos com essa keyword.

> Também não seria um issue do Storefront, o Storefront só mostra os resultados, não processa a busca...

**Comment by ThaisChaves** [comment]
oi @leomp12 !

Entendi. Eu achei que daria para mudar alguma coisa porque se digito clios (sem o I), ele entende e busca a palavra digitada corretamente, como o correto é cílios, achei que ele convertia assim também de acordo com a escrita certa.

Eu fiquei na dúvida de onde abrir o issue, ai abri aqui porque confirmei antes com o Matheus... hehe

Mas blz, vou passar para ela alterar o cadastro. O problema nesse caso que eu achei, seria se ela cadastrar depois um sem o acento e passar batido. Ai quando um cliente buscar, não vai ver os demais.
