### ISSUE TITLE
Erro ao finalizar pedido ausência de 'order_number'

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#436]
Consegui simular poucas vezes, deu apenas 2 erros desse comigo. Depois das duas vezes, não deu o erro mais, que informou primeiro foi o duasxicaras, coloquei aqui porque acredito que toda forma de pagamento para fechar o pedido, tenha que ter o order number, mas quando testei foi com Pix Paghiper.

{"domain":"www.duasxicaras.com.br","lang":"pt_br","utm":{},"items":[{"sku":"25","name":"Cápsulas de Café Espresso Blend Extra Forte","slug":"kit-10-caixas-de-capsulas-de-cafe-compativeis-com-nespresso","price":19.9,"quantity":10,"warranty":"Garantia contra defeitos de fabricação.","pictures":[{"zoom":{"url":"https://ecoms1-nyc3.nyc3.cdn.digitaloceanspaces.com/1137/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png","size":"1200x1200","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"},"big":{"url":"https://ecoms1.com/1137/imgs/big/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png.webp","size":"700x700","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"},"normal":{"url":"https://ecoms1.com/1137/imgs/normal/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png.webp","size":"350x350","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"},"_id":"562960161444031434300000"}],"available":true,"visible":true,"ad_relevance":0,"currency_id":"BRL","currency_symbol":"R$","condition":"new","views":0,"sales":0,"categories":[{"_id":"5f406aa3f023684cdbdbf8a5","name":"Cápsulas","slug":"capsulas"},{"_id":"5f406bd4f023684cdbdbf8c1","name":"Forte","slug":"cafe-forte"},{"_id":"5f3ededff023684cdbdbb2ac","name":"Cafés","slug":"cafes"}],"keywords":["nespresso","cápsulas nespresso","espresso blend","café forte","extra forte"],"brands":[{"_id":"5fd1168969274c73fce5c540","name":"Espresso Blend","slug":"espresso-blend"}],"short_description":"O café em cápsulas sabor Extra Forte une o sabor marcante do café expresso expresso com a intensidade de um café coado feito na hora. Encorpado e forte, agrada ao paladar de quem aprecia um excelente café!","created_at":"2021-03-10T21:35:46.091Z","specs":[{"grid":"compatibilidade","text":"Apenas Máquinas Nespresso"},{"grid":"quantidade_de_capsulas","text":"10"},{"grid":"cafe","text":"100% Arábica"},{"grid":"intensidade","text":"Extra Forte"},{"grid":"origem","text":"Mogiana"},{"grid":"tipo_de_capsula","text":"Plástica perfurada com vedação em alumínio"}],"in_stock":true,"_id":"369885161668910039500000","product_id":"5f78a2187430f92180fa0af9","picture":{"zoom":{"url":"https://ecoms1-nyc3.nyc3.cdn.digitaloceanspaces.com/1137/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png","size":"1200x1200","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"},"big":{"url":"https://ecoms1.com/1137/imgs/big/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png.webp","size":"700x700","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"},"normal":{"url":"https://ecoms1.com/1137/imgs/normal/@v3/1614440303091-cpsula-compatvel-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4.png.webp","size":"350x350","alt":"Cápsula-compatível-nespresso-espresso-blend-extra-forte-cafe-gourmet-arabica-4"}},"max_quantity":821,"kit_product":{"_id":"5f9b895fb2161709fa468fd9","name":"Kit 10 Caixas de Cápsulas de Café Espresso Blend","pack_quantity":10,"composition":[{"_id":"5fe0ed2f69274c73fceb5983","quantity":0},{"_id":"5fe0f08b69274c73fceb5b0d","quantity":0},{"_id":"5fe13ce369274c73fceb7e35","quantity":0},{"_id":"5fe0ee5b69274c73fceb5a2e","quantity":0},{"_id":"5f789d807430f92180fa09ee","quantity":0},{"_id":"5fe13a5369274c73fceb7d8d","quantity":0},{"_id":"5fe0f26769274c73fceb5c2b","quantity":0},{"_id":"5fc6a40569274c73fcdf859e","quantity":0},{"_id":"5f78a2187430f92180fa0af9","quantity":10},{"_id":"5fe13b7b69274c73fceb7dcd","quantity":0}],"price":109.9},"final_price":10.99,"cost_price":0,"gtin":["7898956140047"],"weight":{"unit":"g","value":150},"dimensions":{"width":{"unit":"cm","value":23},"height":{"unit":"cm","value":7},"length":{"unit":"cm","value":15}},"commodity_type":"physical","manage_stock":true,"adult":false,"auto_fill_related_products":true,"total_sold":0,"specifications":{"compatibilidade":[{"text":"Apenas Máquinas Nespresso","value":"apenas_maquinas_nespresso"}],"quantidade_de_capsulas":[{"text":"10","value":"10"}],"cafe":[{"text":"100% Arábica","value":"100%_arabica"}],"intensidade":[{"text":"Extra Forte","value":"extra_forte"}],"origem":[{"text":"Mogiana","value":"mogiana"}],"tipo_de_capsula":[{"text":"Plástica perfurada com vedação em alumínio","value":"plastica_perfurada_com_vedacao_em_aluminio"}]},"meta_description":"O café em cápsulas sabor Extra Forte une o sabor marcante do café expresso expresso com a intensidade de um café coado feito na hora. Encorpado e forte, agrada ao paladar de quem aprecia um excelente café!","meta_title":"Cápsulas Compatíveis com Máquina Nespresso Extra Forte","updated_at":"2021-03-10T21:35:46.091Z","store_id":1137,"min_quantity":1}],"shipping":{"app_id":1244,"label":"Total Express","carrier":"Logística Própria","service_name":"Total Express","service_code":"FROWN4","shipping_line":{"from":{"zip":"05040000","street":"Rua Marina Ciufuli Zanfelice","number":280},"to":{"zip":"30140072"},"delivery_time":{"days":3,"working_days":true},"price":20.94,"total_price":20.94,"custom_fields":[{"field":"by_frenet","value":"true"},{"field":"frenet:took","value":"375"}],"own_hand":false,"receipt":false},"to":{"_id":"319997161012523095000000","zip":"30140072","province_code":"MG","name":"Matheus Guedes","city":"Belo Horizonte","borough":"Lourdes","street":"Rua dos Aimorés","number":21,"default":true}},"transaction":{"app_id":1251,"label":"Pagar com Pix","payment_method":{"code":"account_deposit","name":"Pix - PagHiper"},"intermediator":{"name":"PagHiper","link":"https://www.paghiper.com/","code":"paghiper"},"discount":{"apply_at":"subtotal","type":"percentage","value":5},"icon":"https://us-central1-ecom-pix.cloudfunctions.net/app/pix.png","type":"payment","fetch_when_selected":false,"buyer":{"email":"matheus@e-com.club","fullname":"Matheus Guedes","doc_number":"xxxx","registry_type":"p","birth_date":{"day":30,"month":9,"year":1990},"phone":{"number":"yyyy"}},"billing_address":{"_id":"319997161012523095000000","zip":"30140072","province_code":"MG","name":"Matheus Guedes","city":"Belo Horizonte","borough":"Lourdes","street":"Rua dos Aimorés","number":21,"default":true}},"customer":{"_id":"5ff8902569274c73fcf28d39","main_email":"matheus@e-com.club","accepts_marketing":false,"display_name":"Matheus","name":{"given_name":"Matheus","family_name":"Guedes"},"birth_date":{"day":30,"month":9,"year":1990},"photos":[],"phones":[{"number":"yyyy"}],"registry_type":"p","doc_number":"xxxx","addresses":[{"_id":"319997161012523095000000","zip":"30140072","province_code":"MG","name":"Matheus Guedes","city":"Belo Horizonte","borough":"Lourdes","street":"Rua dos Aimorés","number":21,"default":true}]},"notes":""}

{"status":400,"error_code":"CKT900","message":"Error on 'transaction': Bad-formatted JSON body (POST) or URL query params (GET), details in user_message (MOD901)","user_message":{"en_us":"data should have required property 'order_number'","pt_br":"data deve ter a propriedade requerida order_number"},"more_info":null}

**Comment by leomp12** [comment]
Storefront tem nada nada a ver com isso, nem o checkout, não temos essa propriedade `order_number` (temos `order.numer`), isso é específico do intermediador de pagamento, no caso o PagHiper.

> Estranho é que de fato não mandamos esse `order_numer` pro PagHiper, nunca, em nenhuma ocasião, ou foi uma intermitência deles ou mudaram a API sem versionar.
