### ISSUE TITLE
Erros de usabilidade kit

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#437]
**Descreva o bug e como reproduzir**
Quando clica para comprar o kit, se ele tiver quantidade definida, sem o cliente puder modificar algo, deveria ser adicionado direto no carrinho, caso contrário serão dois cliques.

O segundo ponto que considero ser mais importante que esse é sua aparência. No desktop quando clica em **Comprar** na vitrine ele fica sobreposto a tudo (até ai tudo bem, porque precisa selecionar a quantidade), mas ao clicar em Comprar novamente, o carrinho aparece por trás, não ficando muito claro a inserção no mesmo, conforme a imagem:

![Screenshot (69)](https://user-images.githubusercontent.com/35343551/112630077-e3110b80-8e13-11eb-9c98-41f91707c242.png)

No mobile isso é ainda pior, porque ele fica travado na tela do kit parecendo que houve um erro, você só vê que foi adicionado ao carrinho, quando fecha a tela do kit.

https://user-images.githubusercontent.com/35343551/112631812-1c4a7b00-8e16-11eb-8efa-1425957be77d.mp4

**Comment by leomp12** [comment]
Sempre tem que mandar link de produto de exemplo, é o mais importante pra reproduzir o erro...

> Quando clica para comprar o kit, se ele tiver quantidade definida, sem o cliente puder modificar algo, deveria ser adicionado direto no carrinho, caso contrário serão dois cliques.

Não entendi isso, mas provavelmente com um link eu entenda também.

**Comment by matheusgnreis** [comment]
https://storefront-demo.e-com.plus/kit-miband--airdots

Produtos com variação por exemplo, abre essa aba, você escolhe, clica em comprar e fecha, além de mostrar a inserçao no carrinho. No kit não, você clica e continua na mesma página, sem mostrar carrinho, achando que não houve alteração, pois fica "travado" na tela. No mobile, isso é mais visível
