### ISSUE TITLE
Edições não sendo possíveis via CMS

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#440]
**Descreva o Bug**
Ao acessar o CMS pela URL /admin/, todas as configurações estão em branco, como se tudo estivesse vazio
![Screenshot (79)](https://user-images.githubusercontent.com/35343551/113192284-f3225400-9234-11eb-9447-fa1ae2d47288.png)
E aqui mostra normal: https://github.com/ecomplus-stores/emporio-tia-sonia/blob/master/content/home.json

Já tive algumas lojas reclamando, algumas que eu sabia que mexiam no Github, indiquei o caminho, outras eu que estou tendo que fazer por elas

**Comment by leomp12** [comment]
Não é um erro daqui.
Foi fixado em https://github.com/ecomplus/storefront-starter-views/commit/4c437f6ded00f9ac6eba1550ef0c0a6accdefefc
Pra forçar a atualização imediatemente tem que triggar um update views como [aqui](https://github.com/ecomplus-stores/emporio-tia-sonia/commit/bea14a631c263cabecadcbc1c660e7c8fdaae857) e depois um deploy.
