### ISSUE TITLE
Erro ao mostrar pontos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#475]
![Screenshot - 2021-06-02T172947 849](https://user-images.githubusercontent.com/35343551/120547978-2c5b7980-c3c8-11eb-853e-246233e63df3.png)
Muitas casas decimais mostrando os pontos todos

**Comment by leomp12** [comment]
Problema aí não é muitas casas decimais, como tá configurado esse negócio aí? kkkk

**Comment by leomp12** [comment]
Trem tá elevado a -16, tá configurado certo o percentual de ganho e o ratio dos pontos?

**Comment by matheusgnreis** [comment]
Está 1 para 1 no ratio e 1%, igual no app.

![120547080-008bc400-c3c7-11eb-875b-7eddefc18832](https://user-images.githubusercontent.com/35343551/120549051-7002b300-c3c9-11eb-81f2-3535a6ef373f.png)

**Comment by leomp12** [comment]
Como assim "igual no app"? Se a configuração já era essa não deveria ter chegado nesse valor.
De qualquer forma isso não é um issue do Storefront não.
