### ISSUE TITLE
Ao aplicar os pontos não mostra dedução no total do pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#476]
Antes de aplicar:

![Screenshot - 2021-06-02T173452 258](https://user-images.githubusercontent.com/35343551/120548750-1601ed80-c3c9-11eb-9b17-65c17b357b62.png)

Depois de aplicar:

![Screenshot - 2021-06-02T173527 145](https://user-images.githubusercontent.com/35343551/120548666-fa96e280-c3c8-11eb-9943-dd01d9db0840.png)

O valor total do pedido continua o mesmo, logo, não sabe se gerou dedução ou não.

**Comment by leomp12** [comment]
Não vai mudar o total do pedido, é a mesma coisa de aplicar um desconto, esse total não muda (naturalmente o total do pedido não muda), muda o valor que aperece sendo pago na forma de pagamento (coluna do meio).

**Comment by leomp12** [comment]
O total do pedido de fato não está sendo alterado, só está sendo pago em duas formas de pagamento, cada uma com uma parte do valor.

**Comment by leomp12** [comment]
@matheusgnreis bati o olho no app mas ainda não sei como ficou salvo assim na verdade, depois abre um issue no repo do app por favor colando JSON do customer que tá com esse valor em pontos aí 😬 
Se puder listar os pedidos que você fez no fluxo desse teste vai ser bom também.

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/app-loyalty-points/issues/3 está ai. 
Sobre esse negócio ai de não mostrar nada, eu até entendi que é uma forma de pagamento, mas o leigo não sabe, acredito que precisaria ter algum aviso. Foi a primeira coisa que Blow Hair falou, ele pediu pra outros fazerem os testes e não entenderam também, então ele ficou nessa tecla de que deveria ser mostrado o usuário para o aplicativo ser "funcional", segundo ele.

**Comment by leomp12** [comment]
Mas não é que não mostra nada, mostra sim, só não é aí.
Você viu se esse deploy dele tá atualizado?

**Comment by matheusgnreis** [comment]
Está com a nova versão do storefront template lá no package json e no console log também

**Comment by leomp12** [comment]
Qual é o link da loja?

**Comment by matheusgnreis** [comment]
@leomp12 a principal solicitação do Blow Hair no momento, é que não dá pra pagar o restante e finalizar o projeto, se não der pra ver mudança de valor ali no checkout. Precisa ter uma diminuição do valor, não sendo no desconto, um segundo campo cashback. Até fizemos uma call hoje ele me mostrou que um dos locais que foi o benchmark, lá coloca em desconto, mostrando que teve diminuição do valor.

**Comment by leomp12** [comment]
Uai mas eu tô mexendo nos trem mesmo, inclusive tem um release aí com algumas alterações relacionadas..
Sobre o checkout, mostra o valor sim, eu não falei hora nenhuma que não deveria mostrar uai, mas o total não muda de fato, muda o que está sendo pago via cartão por exemplo, e isso é exibido com a redução:

![Screenshot 2021-06-17 at 19-43-31 My Shop](https://user-images.githubusercontent.com/10326572/122481009-52764180-cfa4-11eb-82e3-e669f3422a3f.png)

> Total: R$ 213,51

Esse é o total sendo pago via cartão, o total do pedido de fato segue sendo **R$ 375,00**, cashback também é dinheiro, isso não é como um desconto via cupom que tem de fato uma redução no valor da compra, certo?

**Comment by leomp12** [comment]
Mas pode abrir uma sugestão da exibição disso no sumário, só não vou exibir como se fosse um desconto porque não faz sentido (não é)...

**Comment by leomp12** [comment]
Agora fiz isso aí no sumário também:
 
![Screenshot 2021-06-17 at 21-46-12 My Shop](https://user-images.githubusercontent.com/10326572/122489520-44312100-cfb6-11eb-84c1-4d970d7a5ca8.png)
