### ISSUE TITLE
Chave de desbloqueio para loja em manutenção

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/storefront#486]
A empresa precisa colocar o site em manutenção, mas ela precisa acessar para ver como está os banners, produtos, dentre outros.
Seria interessante ter a opção para criar uma chave que 'desbloqueie' para que o lojista consiga ver o site.
Sugestão da [comunidade](https://community.e-com.plus/t/nova-pagina-de-manutencao/2164/2).

**Comment by leomp12** [comment]
Acho que só um campo a mais no CMS para o merchant inserir uma senha a ser checada em JS para  exibir a página enquanto a loja está em manutenção...
