### ISSUE TITLE
API Conversão Facebook

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#495]
Vi algumas formas de poder fazer isso, uma delas é utilizando o Google tag manager.
https://www.facebook.com/business/help/702509907046774
https://developers.facebook.com/docs/marketing-api/conversions-api/guides/gtm-server-side#configure-your-gtm-portal
https://github.com/facebookincubator/ConversionsAPI-Client-for-GoogleTagManager/blob/master/template.tpl
Mas nesse caso, utiliza o G4 do google, que vai ser o futuro modelo de traquear eventos.

Pesquisei outro que usa o tag manager:
https://stape.io/facebook-conversion-api-for-bigcommerce/
https://github.com/stape-io/capi-bigcommerce

Fizeram também no shopify
https://github.com/stape-io/capi-shopify

Um serviço que faz isso atraves do tag manager
https://github.com/DeviateLabs/DeviateTracking/blob/main/src/server/deviatetracking.js

Finalmente a API do Facebook Conversões mesmo
https://developers.facebook.com/docs/marketing-api/conversions-api
Parametros: https://developers.facebook.com/docs/marketing-api/conversions-api/parameters

**Existing Pixel Users**
If you have an existing Facebook pixel integration, the Conversion API integration should be built as an extension of the pixel integration, instead of as an entirely different connection.

Pelo que vi, parâmetros iguais (https://developers.facebook.com/docs/marketing-api/conversions-api/guides/end-to-end-implementation)

**Comment by leomp12** [comment]
Uai nú kkk
Precisava só das referências do próprio Facebook mesmo, mas valeu!

**Comment by leomp12** [comment]
### Configuração
- https://www.facebook.com/business/help/1710077379203657
- https://developers.facebook.com/docs/marketing-api/conversions-api/get-started/?translation#via-events-manager

**Comment by leomp12** [comment]
Na verdade isso é server side então tem que ser feito por um app: https://github.com/ecomplus/app-fb-conversions/issues/1
