### ISSUE TITLE
Payment gateway 

### ISSUE THREAD

**Issue by denisdemolli** [ecomplus/storefront#496]
I was not able to find a payment gateway config. How can I set up a payment for the shop? Where can I found the settings to set up the payment gateway config? 
I don't know where I should ask these questions. I have not access to the forum.

**Comment by leomp12** [comment]
Hey @denisdemolli ,

Which gateway do you want to integrate?

You can simply "mock" payment gateways client side only (I can give an example to you) to handle payment buttons such as Stripe.

Or with an [E-Com Plus](https://www.e-com.plus/) merchant account (we can provide it free for dev or a trial for stores in some countries) you can start from https://github.com/ecomplus/application-starter to setup full featured payment gateway apps and install in your store, such as:

https://github.com/ecomplus/app-pagarme
https://github.com/ecomplus/app-mercadopago
https://github.com/ecomplus/app-paypal
...

> I don't know where I should ask these questions. I have not access to the forum.

Currently, forum is open for [E-Com Plus](https://www.e-com.plus/) merchants and partners, we usually don't have technical discussions there either. Best place to ask this would be at repo [discussions](https://github.com/ecomplus/storefront/discussions).
