### ISSUE TITLE
Mensagem enquanto carrega imagem

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#499]
Após alguns vídeos do hotjar, algumas imagens em zoom e na modificação de uma imagem para outro no mobile, as vezes a imagem demora muito pra carregar, ficando no zoom a tela preta com a imagem pela metade ou a tela branca, ao fazer o swipe na troca de imagem no mobile, então talvez fosse interessante colocar uma mensagem aguardando carregamento da imagem, ou algo do tipo.

**Comment by leomp12** [comment]
Funciona apenas quando a imagem é salva no produto com as dimensões (garantido é só pelo admin).
