### ISSUE TITLE
Storefront não atualizando alterações de coleção

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#507]
No painel administrativo foram retirado produtos de uma coleção, conforme print abaixo permanecendo apenas 3:

![Screenshot - 2021-07-31T153031 671](https://user-images.githubusercontent.com/35343551/127749354-07333016-d495-430a-a862-969615d6cb4f.png)

Porém no storefront continua aparecendo várias opções com estoque 0, sem mesmo estar cadastrado na coleção mais.
![Screenshot - 2021-07-31T153134 327](https://user-images.githubusercontent.com/35343551/127749408-7501ba5f-cc36-4c14-b368-61138ce757f6.png)
![Screenshot - 2021-07-31T153245 145](https://user-images.githubusercontent.com/35343551/127749411-4e3d4a8d-a41d-4e6f-82b3-f081ac2ce9a7.png)

**Comment by matheusgnreis** [comment]
A loja é 1035, ultima atualização na loja pelo trigger deploy tem 2 dias, então quando editou a coleção, não atualizou o deploy. Vou  dar um build and deploy pra ver se resolve isso na loja

**Comment by matheusgnreis** [comment]
Na vitrine saiu, mas na coleção continua com todos após https://github.com/ecomplus-stores/kelvys/blob/master/.github/build-and-deploy#L1

**Comment by leomp12** [comment]
Alteração em coleção nunca trigou deploy (já até falei algumas vezes sobre
isso), até poderia ser um enhancement mas é do app GitHub CD, não do
Storefront em si.

E vocês não estão confundindo a página com uma categoria ou marca?
Confirmou que é da mesma coleção? Não deixou o link aqui...

Em sáb., 31 de jul. de 2021 15:50, Matheus Reis ***@***.***>
escreveu:

**Comment by matheusgnreis** [comment]
Foi isso mesmo na categoria. Pra mim na coleção estava rolando também. Então é só isso mesmo, valeu.
