### ISSUE TITLE
Sugestão de Filtro de Preço

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#512]
O filtro de pesquisa, hoje incluem variações, marcas, categorias, mas não existe faixa de preço. Foi sugerido na comunidade um filtro por preço:

![image (7)](https://user-images.githubusercontent.com/35343551/128520888-b4462fda-5f9f-453e-ac4f-899fa52ddb2a.png)

Tópico: https://community.e-com.plus/t/filtro-por-preco/2390

**Comment by leomp12** [comment]
`SearchEngine`
