### ISSUE TITLE
Bug when trying to edit 11+ items on the cart

### ISSUE THREAD

**Issue by ricardocici** [ecomplus/storefront#521]
**Describe the bug**
When trying to add 11+ amount of an item, the minimum value is 1 and I can't delete it to set 20 items for example. Instead of 20, it will be 120.

**To Reproduce**
1. Add an item to the cart
2. Select 11+ qnt
3. Try to erase the actual amount and set amount to 33
4. See error - the amount will be 133 instead of 33. 

**Expected behavior**
When selected 11+ quantity, let the user erase the actual quantity and put the exact amount

**Screenshots**
![image](https://user-images.githubusercontent.com/13444028/129932118-860fdbf4-bd41-463f-a162-b2c53c41499b.png)

Problem occurs on both web and mobile

**Comment by leomp12** [comment]
Aí eu vi issue de qualidade @ricardocici 👏🏾 😄
