### ISSUE TITLE
Cadastro de Clientes > Campo UF não aceita letra minúscula

### ISSUE THREAD

**Issue by ricardocici** [ecomplus/storefront#522]
**Describe the bug**
When creating a new customer, the field UF doesn't accept lower letters, only capital letters.

![image](https://user-images.githubusercontent.com/13444028/130139511-cbb8cb85-4a07-4db1-86de-06cfb119095e.png)

**To Reproduce**
1. Go to Clients
2. Click on New Client
3. Scroll down to Adresses
4. Fill the fields like the screenshot attached

![image](https://user-images.githubusercontent.com/13444028/130139751-75424b08-da4e-4acc-9faa-9d44ffb8b528.png)

**Expected behavior**
The user could register the 'UF' field regardless if its capital or lower letters.

**Screenshots**

**Comment by leomp12** [comment]
Mas pelo que entendi isso é no admin né? Seria um issue daqui https://github.com/ecomplus/admin , vou fechar esse e abrir lá.
