### ISSUE TITLE
Do not validate number on new address

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#523]
**Describe the bug**
When you wanna create an order and you need to insert another address, checkout does not check if you put or not number.

**To Reproduce**
1. Go to checkout
2. Click on **Novo endereço**
3. Insert ZipCode
4. If you click on **Prosseguir**, show that you have to insert number. But if you click on **Prosseguir para pagamento**, will go to another step and number will not be validated. If you click on `checkout__steps` there is the same effect of **Prosseguir para pagamento**

**Expected behavior**
Click on **Prosseguir para pagamento** and validate number before going to another step

**Screenshots**
1) When click on **Prosseguir**:
![Screenshot - 2021-08-20T095710 066](https://user-images.githubusercontent.com/35343551/130236680-b74f0def-2a4a-44f9-96ca-ea4554f5c321.png)
2) When click on **Prosseguir para pagamento**:
![Screenshot - 2021-08-20T100650 406](https://user-images.githubusercontent.com/35343551/130237768-8dbb78c0-6bec-4b4c-b895-4ba3c1dbe3e6.png)

**Comment by leomp12** [comment]
Mas nesse caso na verdade você não está prosseguindo com esse endereço novo, no caso ele não chegou a ser cadastrado, você acabou prosseguindo com o endereço que já estava salvo antes...

**Comment by leomp12** [comment]
Meio que continua sendo possível passar usando o endereço já salvo, mas fiz um trem pra melhorar a usabilidade disso.
