### ISSUE TITLE
Vitrines de produtos não atualizam conforme inserção no painel administrativo

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#529]
**Descreva o bug**
Ao inserir novos produtos ou associar eles a uma categoria, a vitrine continua intacta, mostrando os antigos apenas.

**Como reproduzir**

1. Criar um produto / Associar o produto a uma categoria
2. Vá até sua home e verá que os produtos continuarão os mesmo, se for uma vitrine de lançamento ou uma vitrine de uma categoria. Os produtos são mostrados na loja e na pesquisa normalmente, mas na vitrine em si, não mostra.
3. Só passa a mostrar, após ir em uma categoria e salvar dentro dela alguma alteração, ou realizar alguma modificação na loja.

**Comportamento esperado**
Ao criar um produto, se a vitrine estiver sendo filtrada por produtos novos, é interessante que nela passe a mostrar os novos produtos cadastrados. Se foi criado ou editado um produto e associado a uma categoria, deveria mostrar na vitrine essa atualização.

**Comment by leomp12** [comment]
Na verdade você está falando de estantes (shelfs), não vitrines, e isso não é bug porque elas nunca se propuseram a atuar dessa forma, use _vitrine dinâmica_.

Por performance e SEO as estantes são quase 100% pré-renderizadas, client-side os produtos são atualizados mas não redefinidos, não são feitas (e nem serão) outras buscas, então esses produtos novos apareceriam somente se o index fosse compilado novamente (um novo build) e por enquanto isso não acontece a cada novo produto (não faz sentido fazer isso do jeito mais "óbvio").

A _vitrine dinâmica_ por sua vez vai atualizar dessa forma, ao custo de performance e consequente pior UX e SEO, aí fica a critério do admin usar ela ou triga um build manualmente novo depois de alterações relevantes. Depois ela vai ter mais opções de filtros.
