### ISSUE TITLE
Tag de lançamento

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#532]
Criar uma tag que fica exposto nos produtos da vitrine, que busque a data de criação e se ela for menor que x dias, mostrar a tag. Esses x dias, inicialmente podemos apenas criar uma prop com ela definida. E futuramente, deixar ela a ser escolhida pelo usuário.

**Comment by leomp12** [comment]
Na verdade isso não vai ser muito funcional enquanto o admin enviar PUT para atualizar produtos...

**Comment by matheusgnreis** [comment]
Pois é, eu vi kkk. Pessoal vem pedindo tem tempo, era bem fácil, mais ai quando rodou vi que tinha vários produtos como novos.

**Comment by leomp12** [comment]
Pois é, tem que implementar no admin primeiro um fix pra isso, mas simplemente trocar o método vai introduzir uns bugs eu acho.
