### ISSUE TITLE
Adicionar temporizador no produto

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#554]
Atualmente existe um plugin temporizador que são pra produtos escolhidos para se colocar na home ou demais páginas. Porém seria interessante ter um temporizador semelhante ao que já existe, mas para cada produto. Estilo ao que acontece aqui:

![download (19)](https://user-images.githubusercontent.com/35343551/139680327-b3ec24da-31bd-46b6-b2be-7ffa0d847319.png)

**Descreva a solução**
Basicamente deve respeitar a promoção, conforme o atributo `price_effective_date`. Temos a função onPromotion do [utils](https://developers.e-com.plus/utils/ecomUtils.html#.onPromotion), em que, se for promoção, ele retornará `true` e assim pode mostrar o contador no produto. Esse contador, deve todo dia reinicializar até o fim da promoção (ou seja, a promoção tem prazo de 3 dias, porém todo dia vai ser contado 24 horas para ficar mais apresentável e ter o gatilho de única promoção). 

**Adicional**
Preferencialmente, ter uma `prop` que virá de uma configuração posterior do usuário pra mostrar ou não esse gatilho no produto.

**Comment by leomp12** [comment]
@Mazurco066 quer dar uma olhada nessa task pra nós?
