### ISSUE TITLE
Support "tell me when available" for variations

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#562]
**Is your feature request related to a problem? Please describe.**
Currently we are showing the [_notify me when available_ form](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/widget-offers-notification/src/append/product-slots.ejs#L21-L55) **only when the product itself is out of stock**, but sometimes only some variations are out of stock (a t-shirt out of stock in size M for example, but with stock in size G), in those cases the customer interested in the specific variation needs to be notified when it becomes available again. 

**Describe the solution you'd like**
When customer selects a variation out of stock (`TheProduct` component), the slot `out-of-stock` must always show [offers notification iframe](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/widget-offers-notification/src/append/product-slots.ejs#L22-L55) form, in this case the iframe URL must be dynamic with new `&variationId=` param with current selected variation ID.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/ecomplus/app-offers-notification/issues/12
https://github.com/ecomplus/app-offers-notification/commit/55309e7418b3b4c2a3ce649daa3ec53b5a3282bf

**Comment by Suzei** [comment]
O Storefront não permite selecionar uma variação que tá fora de estoque, ele indica isso colocando o disable na opção. No caso, teria que fazer com que esses disables fossem selecionáveis e aí o `iframe` apareceria? E quanto ao slot do `out-of-stock`, como ele surgiria pro usuário? Com um fade-in, dando refresh na página, por modal, quais são as opções?

![image](https://user-images.githubusercontent.com/55220803/143077936-0d453ed3-4e03-4809-9d38-eb5435227de7.png)

**Comment by leomp12** [comment]
@Suzei os desabilitados devem se tornar clicáveis, o slot `out-of-stock` já está no template do componente [aqui](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-components/src/html/TheProduct.html#L84-L91), não precisa adicionar transição para ele por enquanto, como é um slot você não sabe o conteúdo dele e pode ser um modal sim, mas não vai ser o caso por padrão.

> Refresh na página jamais, na verdade eu não sei se entendi o que você quis dizer aqui...
