### ISSUE TITLE
Desconto não é atualizado após remoção do brinde

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#578]
**Descreva o bug**
Ao remover um produto ou diminuir uma quantidade de um item, para subtotal ficar abaixo do valor da regra, ele retira da lista o brinde, mas o desconto do mesmo continua sendo aplicado no checkout.

**Como reproduzir**
https://www.loom.com/share/76f091e142c3485192d5e79c4b9b8a2e

**Comment by leomp12** [comment]
Não está havendo outro fetch no `apply_discount` depois que esse item é removido, mas acho que é só nesse caso com um brinde nesse valor surreal, em certo momento o total do carrinho fica zerado...
Faz um teste em um cenário mais realista por favor para verificarmos isso.

**Comment by leomp12** [comment]
Era justamente por causa do total zerado por causa do desconto enorme do brinde aí...
