### ISSUE TITLE
Account subscription orders

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#660]
**Is your feature request related to a problem? Please describe.**
Following implementation of https://github.com/ecomplus/app-galaxpay , we need separated tab on account view or just custom highlight on orders list for subscription (recurrence) orders.

**Describe the solution you'd like**
Customer must be able to see with easy witch orders are subscriptions, cancel them (normally) and also list all past payments (other orders) related to some subscription.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/ecomplus/app-galaxpay

**Comment by leomp12** [comment]
Algum comentário adicional @wisley7l ?

**Comment by wisley7l** [comment]
A principio, que os novos pagamentos da recorrência são novas _orders_ e que as informações da _order_ original (assinatura) serão armazenadas na  propriedade _subscription_order_ de cada novo pagamento, ou seja, de cada nova _order_ gerada.

**Comment by leomp12** [comment]
Mais um detalhe, a tab de assinaturas não deve aparecer sempre porque na maioria dos casos as lojas não têm assinatura mesmo, então antes de mostrá-la devemos verificar se o cliente tem pedidos recorrentes com uma primeira request:

```js
ecomPassport.requestApi(`/orders.json?transactions.type=recurrence&limit=1&fields=_id`)
```

Que deve retornar um ID de pedido recorrente, se o cliente tiver pelo menos uma assinatura feita...
