### ISSUE TITLE
Duplicação de evento Google Analytics

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#702]
**Descreva o bug**
Ao recarregar a página de confirmação, está disparando outro evento purchase.

*Comportamento correto*
Como muitos usuários hoje são de celulares, então se a pessoa compra, sai do site indo pro whatsapp e depois volta pro site, possivelmente vai recarregar a página automaticamente e ai vai gerar outra conversão. No caso, não deveria.

**Comment by matheusgnreis** [comment]
Deve ocorrer semelhante para facebook tbm, mas agora temos ai o event id pra isso, deve desconsiderar.

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/dabbc5fd1e475db98e8a6e475a02fbecdf6ac181
