### ISSUE TITLE
Não checar quantidade do item da variação no carrinho

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#703]
**Descreva o bug**
Atualmente se o produto tem variação e o mesmo está esgotado e tiver esse item em um carrinho, o cliente consegue chegar até o checkout e por vezes finalizar o pedido (o preço cobrado é apenas do frete a depender da forma de pagamento).

**Como reproduzir**
Guia anônima https://www.usetrucco.com.br/app/#/cart/627ae35f3da6d37bc22cb501

Como pode ver, além de estar esgotado, o carrinho permite inserir 6 unidades do produto, que corresponde justamente a quantidade de unidades que o produto tem e não a respectiva variação.

**Comment by leomp12** [comment]
Na verdade ele checa mas tá sobrescrevendo com a do produto, vou fixar mas o deploy dessa loja está muito desatualizado.
