### ISSUE TITLE
[RFC] ECom.Beauty fine tune

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#706]
O que ainda falta ou pode ser melhorado para o tema seguindo o protótipo?
https://xd.adobe.com/view/a6ede39e-9ce6-4cf7-aa10-f5cbea3d2c49-f3be/screen/b263e48d-cf5a-422c-83b9-756b79572378/

> Algumas coisas não dependem apenas de CSS e serão possíveis depois de https://github.com/ecomplus/storefront/issues/705 e improves de alguns widgets.

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/preview/settings/lib/color-functions.js#L125

**Comment by vitorrgg** [comment]
Fiz [este deploy](https://ecombeauty.netlify.app/) usando o tema e os banners e produtos para tentar chegar o mais próximo possível do design feito. 

Sugestões para ficar mais fiel ao design: 
- Na top-bar__countdown o tamanho da fonte do design é um pouco menor, pelo que testei fica mais próximo como `0.7rem`;

- O `font-weight` do tema está maior que o do design em alguns pontos como na `top-bar__page-links` e `info-bar__item`. O font-weight nesses casos é 700 e pelo que testei com 500 ficaria mais próximo;

- O card de blog posts no design exibe imagem e título que hoje mostram junto com data de criação e um link "continitue lendo"  escondendo o `card-text`; 

design: ![image](https://user-images.githubusercontent.com/35348281/168854318-9546011e-200c-4191-9db1-81cd5c31051f.png)
atual: 
![image](https://user-images.githubusercontent.com/35348281/168854240-9a5884f5-6c79-48aa-ac50-13797b96bd93.png)

Não tem a ver com o tema, mas acho interessante indicar qual o pacote de ícones do tema de alguma forma, talvez no nome dele no CMS para que o cliente configure e fique mais parecido possível com o exemplo

**Comment by leomp12** [comment]
@sameoldcarlos dá uma olhada nas sugestões por favor? O deploy https://ecombeauty.netlify.app/ deve ajudar bastante, source aí https://github.com/ecomplus-stores/beauty-theme/tree/master/content caso você queira copiar pra testar localmente.

---

> Não tem a ver com o tema, mas acho interessante indicar qual o pacote de ícones do tema de alguma forma, talvez no nome dele no CMS para que o cliente configure e fique mais parecido possível com o exemplo

@vitorrgg é `line-awesome` nesse caso, mas tem a opção no CMS de _padrão do tema_ nos ícones:

![Screenshot 2022-05-17 at 22-04-39 My Shop](https://user-images.githubusercontent.com/10326572/168936292-97cfbba3-4132-4e4d-af07-1dd332653eab.png)

Um field no CMS mudar o outro não é trivial, tem que criar um widget (React component) só pra isso, nesse momento é um trabalho que não vale a pena.

A mesma coisa acontece com fontes, o _padrão do usuário_ na verdade não está forçando padrão do sistema (acho que deveria) quando há tema, nesse caso usa a fonte do tema, talvez depois adicionamos nele um _padrão do tema_ separado do _padrão do usuário_ (que nesse caso vai forçar o uso da fonte do sistema) também.

Inclusive, o _padrão do tema_ é a opção que fica selecionada por padrão https://github.com/ecomplus/storefront-starter/blob/master/content/settings.json#L9-L10, se o usuário não forçar outra fonte e escolher um tema, a loja vai usar as fontes do tema.

**Comment by leomp12** [comment]
Pro próximo então @sameoldcarlos ? 😄
