### ISSUE TITLE
Error at product offer countdown

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#722]
**Describe the bug**
Sometimes, when config product discount we have:
![image](https://user-images.githubusercontent.com/35343551/170991752-e9df1255-f1c6-48c0-b8e3-5d77b0e94a7e.png)
Sometimes pass after hours, sometimes not

**Comment by leomp12** [comment]
Põe um link de exemplo aí por favor

**Comment by matheusgnreis** [comment]
https://www.belavirtuosa.com.br/vestido-tubinho-vermelho-com-babados-nas-mangas
