### ISSUE TITLE
Replace Universal Analytics with GA4

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#736]
After 1/07/2023 Universal analytics will not work anymore.
https://support.google.com/analytics/answer/10759417?ref_topic=10737980?utm_campaign%3D2022-q1-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga-deprecation-comm-ua-only

**Comment by leomp12** [comment]
@wisley7l no embalo do GA4? 😄

**Comment by matheusgnreis** [comment]
Bom, acho que o certo seria colocar um novo e não substituir, porque se não de muita gente vai dar pau. Só avisamos que o outro vai parar de funcionar

**Comment by leomp12** [comment]
Via GTM, opção de config do widget tag manager https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/content/widgets/tag-manager.json

**Comment by leomp12** [comment]
> Observação: o GA4 é compatível com o esquema de comércio eletrônico do UA, mas este não é compatível com o esquema do GA4. Se você inseriu tags no seu site para propriedades do GA4 com o UA, não substitua os esquemas mais antigos por tipos de dados de comércio eletrônico do GA4.

Tem que fazer algo mesmo? 😄 🤔
