### ISSUE TITLE
Erro no cálculo do frete para produtos com kit

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#739]
**Descreva o bug**
Ao realizar o cálculo na página de produto, considera os preços dos produtos individualmente, ao invés do produto kit, logo, se a loja tem alguma regra de frete grátis acima do valor x, mostra frete grátis e quando chega no checkout não tem  por conta do kit

**Comment by leomp12** [comment]
Tem algum exemplo?

**Comment by matheusgnreis** [comment]
https://www.emporiotiasonia.com.br/combo-especial-cafe-da-manha---tia-sonia

**Comment by leomp12** [comment]
Na verdade o problema é que está enviando quantidade 5 do produto kit no exemplo aí, e portanto o subtotal dá 400 e alguma coisa. O preço do kit bate com a preço dos items separados, o que está errado é a quantidade enviada nesse cálculo.

**Comment by matheusgnreis** [comment]
Sim, mas como resolver?
Porque na configuração do produto, precisamos colocar 5 itens mínimos e quantidade 5 para poder fixar o kit em 5 com quantidade mínima e máxima a ser escolhida

**Comment by leomp12** [comment]
Fixando os items que passa pro cálculo de frete no componente ué 😄
