### ISSUE TITLE
[RFC] Recurrence

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#767]
**Is your feature request related to a problem? Please describe.**
Show better recurrence payment methods on checkout

**Describe the solution you'd like**
List all payment methods, but if it is recurrence show one recurrence credit_card &/or banking_billet &/or account_deposit and then inside of form, people can select monthly or annually.

Or

List all payment methods, but if it is a recurrence, show only one recurrence payment method, and inside of form, people can select monthly or annualy and type of payment and then pay.

or something else

**Comment by leomp12** [comment]
Por que mostrar só cartão OU boleto OU pix OU ... ?
Não é mais fácil nesse caso o próprio lojista desabilitar no app?

**Comment by leomp12** [comment]
Aí selecionando o método de pagamento, seja por boleto, cartão ou etc, abriria o form pra selecionar o período...

**Comment by matheusgnreis** [comment]
Então, problema que ele pode usar cartão, boleto e pix. 
Nesse caso, abriria um pra cada. Buscaria os períodos, cliente selecionava a forma de pagamento, selecionava o periodo e digitava o cartão pra finalizar, se for para cartão de crédito

**Comment by leomp12** [comment]
> Então, problema que ele pode usar cartão, boleto e pix.

Não saquei porque isso é problema na real.

> Buscaria os períodos

Como assim buscaria pedidos? Isso tem que ser mockado ou vir do list payments, não é pra ter que buscar pedidos assincronamente quando selecionar forma de pagamento não.

--- 

Eu entendo que talvez seja melhor ele selecionar se quer assinatura primeiro e depois seguir para o pagamento, mas talvez isso seja melhor em um segundo passo, teria que mexer no fluxo do checkout...

**Comment by matheusgnreis** [comment]
> Eu entendo que talvez seja melhor ele selecionar se quer assinatura primeiro e depois seguir para o pagamento, mas talvez isso seja melhor em um segundo passo, teria que mexer no fluxo do checkout...

Sim, concordo. Mas é um trabalho maior. Acho que é num segundo step mesmo.



> Como assim buscaria pedidos? Isso tem que ser mockado ou vir do list payments, não é pra ter que buscar pedidos assincronamente quando selecionar forma de pagamento não.
O que estou fazendo agora é, um computed que lista pra mim as formas de pagamento via assinatura, por método de pagamento (cartao ou pix ou boleto) e agrupo nesses 3 os seus respectivos, exemplo, listo lá credit_card: [mensal, bimestral], banking_billet: [], account_deposit: []. Também tenho um shouldUseRecurrenceForm, que pega o paymentGateway escolhido e verifica o type, se for recurrence, é true, pra mostrar o componente que basicamente está sendo o select abaixo:
![image](https://user-images.githubusercontent.com/35343551/182933633-6067c1cb-f1cd-4769-bb3e-4772fdc8f6d1.png)

No select, planejo renderizar os 'periodos' que estão no primeiro computed que mostrei, baseado no payment_method.code do paymentGateway escolhido. Não sei se deu pra entender

**Comment by matheusgnreis** [comment]
No list payments nao tem informação de mensal, semestral e afins, somente temos ali o nome da forma de envio, assim como na prop que lista todas as formas de pagamento.

**Comment by leomp12** [comment]
Então você tá mockando... A princípio pode ser, ideal seria vir do list payments pra ser configurável (eu sei que não tem no schema, ainda), mas eu só falei isso porque quando vocế disse "_buscaria os períodos_" achei que estava pensando em bater em algum endpoint do gateway.

**Comment by leomp12** [comment]
![Screenshot 2022-10-25 at 22-35-15 My Shop](https://user-images.githubusercontent.com/10326572/197913881-14cfb3f9-25ae-4a7f-9f42-e4fa9de0ce90.png)

**Comment by leomp12** [comment]
Tá pegando os períodos pelas opções que estão vindo no list paytments mesmo.
Consegue ver se tem mais alguma ideia e me ajudar a testar por favor @matheusgnreis ?

**Comment by matheusgnreis** [comment]
Deu erro com boleto, porque parece que só mostra no credit card

**Comment by matheusgnreis** [comment]
Só a tia sonia que usa, então, teria problema não

**Comment by matheusgnreis** [comment]
Acho que só colocaria um label ali, **Frequência da sua Assinatura**, alguns como a natone coloca isso lá no carrinho.
O ícone desse ai está bem melhor, foi um até que colocamos la na tia sonia, que dá mais ideia de recorrencia.

Não dá pra testar por conta do token, segundo checkout. No caso, pra testar seria substituindo componentes lá na tia sonia?

**Comment by matheusgnreis** [comment]
Vi que é meio que tendencia colocar o botão assinar na página do produto, para chegar no checkout, já filtrado. Mas isso é tranquilo até, dá para fazer isso no front. Droga raia funcionava igual o nosso, mudaram para esse formato em produtos selecionados, natone o mesmo

**Comment by leomp12** [comment]
> Deu erro com boleto, porque parece que só mostra no credit card

Verdade, não vou agrupar por padrão quando houver assinatura em outro método de pagamento.

> Vi que é meio que tendencia colocar o botão assinar na página do produto, para chegar no checkout, já filtrado. Mas isso é tranquilo até, dá para fazer isso no front. Droga raia funcionava igual o nosso, mudaram para esse formato em produtos selecionados, natone o mesmo

Isso é outros 500 né, a princípio não vai ser assim no template padrão não, customização...
