### ISSUE TITLE
Erro na troca de endereço

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#783]
**Descreva o bug**
Alguns clientes mais espertos estavam colocando um endereço mais perto e outro mais longe. Fazia a troca e tirava a foto, enviava para o lojista informando que queria o preço da tela que estava errado, pois não havia re-calculo. Aparentemente no update zip code, o this.shippingAddress era o antigo ainda, por isso coloquei um setTimeout com um pequeno delay, para dar tempo a propriedade mudar o valor dela e assim, atualizar o localZipCode, que é enviado para o shipping calculator que está no watch para submeter o cálculo, quando for modificado.

**Comment by leomp12** [comment]
Tá mas o certo seria você identificar porque o `this.shippingAddress` estava atrasado e corrigir "na raiz", o momento em que o método `updateZipCode` é chamado, certo? E por corrigir eu não digo mockar um timeout também 😬 
Provavelmente mudar o local em que o método é chamado ou aguardar o próximo ciclo com `$nextTick` https://vuejs.org/api/general.html#nexttick

**Comment by matheusgnreis** [comment]
Eu olhava e estava lá correto o shippingAddress. Mudei ele aqui de lugar, que é o que faz sentido na real. Porque o this.shippingAddress precisa do this.selectedAddressId para buscar o endereço correto. E estava sendo feito o updateZipCode, sem o this.selectedAddressId estar setado ainda.

**Comment by matheusgnreis** [comment]
Parece legal o nextStick, acabei de ler mais sobre ele. Vou ler a doc direitinho depois
