### ISSUE TITLE
Updated sass package crashed npm i

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#886]
**Describe the bug**
After searching which package was crashed, i saw cssnano today is 5.x but last package-lock json was 4.0.0 and then he used with https://github.com/intervolga/optimize-cssnano-plugin and then another one with css too, so started to look something with css package, and then sass was the problem.

**To Reproduce**
1. Clone current repo
2. npm i

**Screenshots**
Also tried with gitpod and i had problems too.
<img width="958" alt="Captura de tela 2023-04-03 111928" src="https://user-images.githubusercontent.com/35343551/229564333-1689fb65-9cf6-4d98-99ba-dee8125c9371.png">

I dont know if i need to change cssnano too, but just replacing current version of sass to 1.58.3 and run npm i, worked.

**Comment by leomp12** [comment]
No meu ambiente segue funcionando normalmente, tanto install, quanto serve e build.
Testei no Gitpod e também funcionou normalmente.

![Screenshot 2023-04-03 at 13-23-31 Welcome - storefront - Gitpod Code](https://user-images.githubusercontent.com/10326572/229569817-d128c95e-4acd-48a8-8763-41768a95741d.png)

A descrição do issue aqui tá muito confusa, nem entendi o que exatamente você olhou no `package-lock.json` inclusive, e pode (na verdade deve) ter várias versões da mesma dependência lá (em pacotes diferentes).
No seu print o erro era do nvm instalando o Node 14, provavelmente só uma instabilidade momentânea do npm ou de rede do próprio Gitpod mesmo, tem nada a ver com as dependências do repositório, nem chegou a tentar instalar elas.
Vou fechar...
